### ISSUE TITLE
How to add query parameters (video- and audio-downloads)?

### ISSUE THREAD

**Issue by Swallenberg** [peak3d/inputstream.adaptive#1004]
Hi,

Thanks for the excellent plugin. I have a question about adding query parameters to Inputstream when downloading audio and video segments. Hope you can help me out.

The problem is that Inputstream no longer can download files from the source I am using, because the server now demands a query parameter for all files, except for manifest.

This is how it should look like to work (just an example):
.../audio_dk_aac_224/init.cmfa?ch_SessionId=74a1b549-2133-4495-be93-b9aaa036ebad

Now Inputstream throws an 404-error because it doesn't have the **ch_SessionId** parameter .

Can I add the parameter to Inputstream somehow? I have read the Wiki, but I am a bit lost how to do it, or if it is possible.

Your help is appreciated.

**Comment by CastagnaIT** [comment]
have you already tried add into stream_headers param?
https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivestream_headers

**Comment by Swallenberg** [comment]
> have you already tried add into stream_headers param? https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivestream_headers

I have tried to send it as a custom header with stream_headers. No luck, unfortunately.

**Comment by CastagnaIT** [comment]
please attach the manifest as text file so we can understand better the situation

**Comment by Swallenberg** [comment]
> please attach the manifest as text file so we can understand better the situation

Here it is: 
[manifest.txt](https://github.com/xbmc/inputstream.adaptive/files/8869909/1.txt)

I'm not sure if it helps in this matter though. The missing query parameter can't be extracted from the manifest, correct me if I am wrong.

**Comment by CastagnaIT** [comment]
since there are a lot of use cases is needed to know what is the manifest content
are you sure that this "SessionId" value appended in urls is fixed until the end of video?
because i know that some services set an expire time to parameters and the value need to be renewed
this is important to know

a possible solution is that your addon act as proxy to get manifest and streams data,
then you have to replace `BaseURL` in manifest with your proxy address, so you will have to implement a service in your addon to provide a proxy that will route the ISA http requests to the service provider by appending in the http requests the ch_SessionId param value,
something like the example https://github.com/xbmc/inputstream.adaptive/wiki/How-to-provide-custom-manifest-and-license

maybe @glennguy can give some other hints

**Comment by glennguy** [comment]
What @CastagnaIT said is probably what you'll have to do - run a proxy as a service for your addon to modify the manifest to add this parameter. @matthuisman have you had this issue before in any of your add-ons?

**Comment by matthuisman** [comment]
@Swallenberg 
If you append the params to the manifest url, you may find the urls inside the manifest get generated with the same params. Failing that, I believe your own proxy is only solution
