### ISSUE TITLE
Where are files created by IA (widevine license) in KODI 20?

### ISSUE THREAD

**Issue by mbebe** [peak3d/inputstream.adaptive#1058]
In kodi 19 these 3 files  (xxx.challenge , xxx.response, xxx.init ) were in ..KODI19\KODI\portable_data\cdm

In Kodi20 this folder is without these files.
I created portable version with shortcut and added -p and the end.
Where i should look for them?

**Comment by glennguy** [comment]
Was disabled in https://github.com/xbmc/inputstream.adaptive/pull/770

If it would be useful I'd happily accept a PR to place it back, maybe also being behind a setting (would do myself but very short on time at the moment)

**Comment by CastagnaIT** [comment]
you cannot make it as setting without messing up a large part of the code since ssd project is separate project/interface
that IMO this is not the case

we should think to about merging the two projects first
after that the setting can be added in clean way

meantime who need debug data must compile ISA by enabling the define

**Comment by glennguy** [comment]
Thanks @CastagnaIT 

On a side note I'm looking at merging the two projects at the moment (very slowly)

**Comment by CastagnaIT** [comment]
you could also reuse `GLOBAL::Host` but i would prefer to avoid it

> On a side note I'm looking at merging the two projects at the moment (very slowly)

is another good long job :)
