### ISSUE TITLE
2.1.11 on Krypton

### ISSUE THREAD

**Issue by troqnec** [peak3d/inputstream.adaptive#107]
Hi friends, how I can compile 2.1.11 on Krypton. After 
git clone https://github.com/peak3d/inputstream.adaptive.git
I checkout branch with:
git checkout -b Krypton origin/Krypton
But with this I can install version 2.0.19 and this is not helping me becouse I need version 2.1.. My kodi version is 17.4. Sorry for my English and Thanks in advance

**Comment by DjDiabolik** [comment]
I thinks a very good idea/suggestion but i don't know if it's possible to do.....

Because it's not possible to install/update inputstream as like an "normal" addons ?? Right now inputstream it's incorporated on kodi code right ? But if possible to make it installable as external all we can update our setup release after release whitout wait every kodi new version relased.....

**Comment by troqnec** [comment]
Hi DjDiabolik, I installed kodi from slackbuild and I think that inputstream is like normal addon...I dont know why they say that is binary addon when I don't have inputstream in kodi 17.4 To have this addon I make:
1. git clone https://github.com/xbmc/xbmc.git
2. git clone https://github.com/peak3d/inputstream.adaptive.git
3. cd inputstream.adaptive && mkdir build && cd build
4. cmake -DADDONS_TO_BUILD=inputstream.adaptive -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/project/cmake/addons
5. make
But Now I have 2.0.19 version...I just need 2.1 version.

**Comment by DjDiabolik** [comment]
You have compiled inputstream.... not installed like another addons from kodi repo. It's not my idea.

**Comment by peak3d** [comment]
2.1.11 is not compatible with Kypton.
