### ISSUE TITLE
Possibility of implementing widevine support on iOS and Apple TVOS

### ISSUE THREAD

**Issue by RHStonks** [peak3d/inputstream.adaptive#1131]
https://github.com/xbmc/inputstream.adaptive/pull/722#issuecomment-1417743700

Someone mentioned about the possibility of adding widevine support for iOS and TVOS due to youtube ios app containing the following framework "widevine_cdm_secured_ios.framework"

May also have a similar framework on Youtube Apple TVOS app as well. 

Let me know if it's possible to add widevine support on iOS and TVOS. Would make both iOS and TVOS more useful when using Kodi.

**Comment by glennguy** [comment]
This won't be possible unfortunately. We'd need an SDK from Google for this, it's not open source and we'd need to pay $$$ and sign license agreements etc.

The best bet would be a Fairplay implementation. Before you open an issue asking for that feature, neither of us (myself and @CastagnaIT ) are Apple guys and have limited/no experience doing dev work for Apple devices. It would be a different story if Kodi was in the App store because there would be a much wider audience and a better effort/payoff scenario.

**Comment by Spider-netizen** [comment]
> The best bet would be a Fairplay implementation. Before you open an issue asking for that feature, neither of us (myself and @CastagnaIT ) are Apple guys and have limited/no experience doing dev work for Apple devices. It would be a different story if Kodi was in the App store because there would be a much wider audience and a better effort/payoff scenario.

I'm willing to try and help implement this but I will need some guidance where to start.
