### ISSUE TITLE
While using youtube playback using MPEG-DASH the Video has to buffer while skipping forward.

### ISSUE THREAD

**Issue by GrimChaos** [peak3d/inputstream.adaptive#1194]
### Describe the bug
Here is a clear and concise description of what the problem is:
Internet 300 Mbps down and up. Started happening about 2-3 weeks ago.

-In Youtube, seeking in a Video takes 5-10s until video playback resumes.  
-Audio is available and audible many seconds before video is shown / has caught up. 
-Scrubbing ahead doesn't work as well. Holding (or pressing a few times) the skip forward x seconds, it doesn't skip forward more than once (mine is set to 30 seconds). I don't know if I explained it clearly but I tried.
-Disabling MPEG-DASH, the playback will work fine again (looks much worse at 720p).  Turning MPEG-DASH back on it happens again.

Other people that have/had this problem (for some people it started working again).
https://github.com/anxdpanic/plugin.video.youtube/issues/426

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video not to be delayed by about 5-10 seconds.

## Actual Behavior

In Youtube, seeking in a Video takes 5-10s until the video playback resumes.  

## Possible Fix

Disabling MPEG-DASH, the playback will work fine again (looks much worse at 720p).  Turning MPEG-DASH back on it happens again.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/hunofilike

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 9 - On a Mediabox x95 Max
 - Kodi version: 20.1 (but started on 19.5)
 - inputstream.adaptive version: 20.3.5

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

Thanks, you guys are amazing!

**Comment by jmbreuer** [comment]
Same thing happens on LibreELEC / x86_64-Generic.

**Comment by CastagnaIT** [comment]
i think this issue is not yet relevant
fwik at today youtube provide HLS manifests

i have tested 4k videos on a android 9 device, without using Youtube addon, so by using a direct STRM with manifest link
and i can play it without any type of buffering, also video seek works correctly with a max delay after seek of 1 second
this by using a 4g connection so not cabled fiber internet

EDIT: if you want to test, current ISA Nexus release have HLS-VP9 broken, you need use current nightly with fix:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Nexus/282/artifacts

**Comment by MoojMidge** [comment]
> i think this issue is not yet relevant
> fwik at today youtube provide HLS manifests

YouTube provides both HLS and MPD manifests for live streams only, depending on the client being used. The HLS manifests only appear to use H.264 video streams for live videos, while the MPD manifests also provide VP9 live streams (real time transcoding by YouTube?)

Youtube only provides HLS manifests for VOD if Kodi pretends to be an iOS Youtube client, and only recently have VP9 video streams been included in the HLS manifests as iOS previously didn't support this. Not sure if this is officially stated as being supported in the Apple docs, but it works for newer iOS versions. I don't think AV1 video streams are provided by the HLS manifests yet. 

The YouTube addon creates MPD manifests from the available VOD video streams for playback using ISA, but the problem reported by OP was caused by YouTube throttling the video streams and is not a problem with ISA.

There is a separate problem with ISA not properly detecting and updating the correct segment for dynamic MPD manifests used for live streams, but I think the recent work on that in ISA may have fixed the problem. I'll try and test this using the nightlies and create a test case if this is still a problem.

**Comment by CastagnaIT** [comment]
thanks for clarification

> There is a separate problem with ISA not properly detecting and updating the correct segment for dynamic MPD manifests used for live streams, but I think the recent work on that in ISA may have fixed the problem. I'll try and test this using the nightlies and create a test case if this is still a problem.

yeah if needed open an Issue
thanks
