### ISSUE TITLE
Enhancement: Use N concurrent connections to download segments

### ISSUE THREAD

**Issue by TheTyrius** [peak3d/inputstream.adaptive#1386]
Some internet-connections have very limited speed for sequential segment download, and can only reach rated speeds using multiple simultaneous connections.
Currently it seems to me that all segments are downloaded sequentially, with one connection per segment (this seems to use kodi internals via cfile, where I could not find any options regarding this).

It would be great if there was a optional inpustream setting to use 3-5 concurrent connections (ideally buffering ahead multiple segments _in parallel_). Optional because I understand this may not make sense for all kinds of streams/addons.

I don't know a lot about HLS etc, please let me know if such parallel buffering is at all possible with these technologies.

Kind regards :)

**Comment by CastagnaIT** [comment]
imo parallel downloads make no sense because we need data in sequential order
so if one chunk is not completed yet, while in parallel more next chunks have been downloaded, for any reason in advance, the playback will stall, there are no improvements

having multiple parallel downloads can makes the situation worse,
download each additional chunk in parallel will halve your network bandwidth and the download time will be doubled, tripled, etc... So we may lose the download speed on the currently required chunk

to mention that some CDNs may not like parallel downloads because it means multiple server connections for a single playback

what you need is the adaptive streaming (already implemented but probably not very optimized https://github.com/xbmc/inputstream.adaptive/wiki/Setting%3A-Stream-selection-type#adaptive)
has the purpose to adapt video quality in realtime according to the bandwidth available (if you play streams with multiple quality)

different is the situation if it is the video provider CDN that has bandwidth problems
in this case (and not all manifest streams support it) we should fallback to a different CDN (like BaseURL on DASH)
but this is currently not implemented in ISA maybe in future

**Comment by TheTyrius** [comment]
> we need data in sequential order so if one chunk is not completed yet, while in parallel more next chunks have been downloaded, for any reason in advance, the playback will stall, there are no improvements

I agree.

> having multiple parallel downloads can makes the situation worse, download each additional chunk in parallel will halve your network bandwidth and the download time will be doubled, tripled, etc... So we may lose the download speed on the currently required chunk

Ideally yes. But in some situations a few parallel connections can be beneficial to overal bandwidth, scaling almost linearly up to the full rated bandwidth of the connection (a quick search turned up some user examples via the links in https://github.com/jellyfin/jellyfin/issues/3206). I realize this is not an ideal network condition and would only workaround an underlying issue. 

Thanks for having a look though! I've spend a little more time looking at the downloader code and I think adding this option would not be trivial given the current architecture. I will therefore pursue different optimizations first. I'll close this issue for now, as I do not know if/when I'll have the time to experiment with implementing this myself.

Have a nice day, and thanks to everyone working on the ISA and broader Kodi ecosystem :)
