### ISSUE TITLE
HDR Playback From Youtube - Issues

### ISSUE THREAD

**Issue by ilikenwf** [peak3d/inputstream.adaptive#1410]
---
name: Problem report
about: Create an extensive report to help us document a problem

---

### Describe the bug
My issue is more or less exactly like [this GitHub issue](https://github.com/xbmc/xbmc/issues/23649) but in regard to an Arc A380. I have an existing issue here: https://github.com/xbmc/xbmc/issues/23957 but am starting to think something about the mpd file or one of the containers in use may be causing the problem now.

Another issue is that the Youtube plugin doesn't really allow for or select all possible formats, so I can't test against 1440p HDR or lower, or select anything other than 4k HDR or 1080p non-HDR.

Everyone has been quick to say it's the fault of my drivers or of the Arc A380 I use, but I'm starting to think this is not the case.

If I use yt-dlp to get the raw URL for just the 4k HDR video, it will stream and play properly, albeit without audio, I do this the lazy way with my 90% AI authored streaming plugin: https://github.com/ilikenwf/plugin.video.youtubedlstreamer

### Expected Behavior
I expected the video and audio to play back in HDR mode, which is sometimes the only way to get 4k playback at all.

### Actual Behavior
As mentioned above, I encountered the issues described.

### Possible Fix
Turning off HDR works, however the Youtube plugin won't really give me any other HDR formats to select and test against while using DASH.

### To Reproduce
To reproduce the behavior:
1. Use Youtube, DASH, Inputstream Adaptive with VAAPI on an Arc A380.
2. I've tried different kernels, both stable and git versions of Kodi and inputstream adaptive.
3. I've tested various configurations but still face the same issue. The h.264 version of the video plays fine but doesn't allow for HDR from YouTube.

Here's an example video that gives me trouble in webm/vp9 mode: [Troublesome Video](https://www.youtube.com/watch?v=VO8Bk03Xv90)

### Debuglog
[kodi.log.zip](https://github.com/xbmc/xbmc/files/13187045/kodi.log.zip)

**Comment by ilikenwf** [comment]
In fact, if I set the youtube addon to ask me for the quality I want, it doesn't even come close to listing all these. It only gives the mpd container as available for 4k HDR.

```
[info] Available formats for VO8Bk03Xv90:
ID  EXT   RESOLUTION FPS HDR CH │    FILESIZE    TBR PROTO │ VCODEC           VBR ACODEC      ABR ASR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb3 mhtml 48x27        0        │                    mhtml │ images                                   storyboard
sb2 mhtml 80x45        0        │                    mhtml │ images                                   storyboard
sb1 mhtml 160x90       0        │                    mhtml │ images                                   storyboard
sb0 mhtml 320x180      0        │                    mhtml │ images                                   storyboard
233 mp4   audio only            │                    m3u8  │ audio only           unknown             Default
234 mp4   audio only            │                    m3u8  │ audio only           unknown             Default
599 m4a   audio only          2 │     2.04MiB    31k https │ audio only           mp4a.40.5   31k 22k ultralow, m4a_dash
600 webm  audio only          2 │     2.10MiB    32k https │ audio only           opus        32k 48k ultralow, webm_dash
139 m4a   audio only          2 │     3.24MiB    49k https │ audio only           mp4a.40.5   49k 22k low, m4a_dash
249 webm  audio only          2 │     3.13MiB    47k https │ audio only           opus        47k 48k low, webm_dash
250 webm  audio only          2 │     4.15MiB    63k https │ audio only           opus        63k 48k low, webm_dash
256 m4a   audio only          6 │    12.94MiB   195k https │ audio only           mp4a.40.5  195k 24k low, m4a_dash
140 m4a   audio only          2 │     8.58MiB   129k https │ audio only           mp4a.40.2  129k 44k medium, m4a_dash
251 webm  audio only          2 │     8.27MiB   125k https │ audio only           opus       125k 48k medium, webm_dash
380 m4a   audio only          6 │    25.47MiB   384k https │ audio only           ac-3       384k 48k high, m4a_dash
328 m4a   audio only          6 │    25.47MiB   384k https │ audio only           ec-3       384k 48k high, m4a_dash
258 m4a   audio only          6 │    25.71MiB   388k https │ audio only           mp4a.40.2  388k 48k high, m4a_dash
17  3gp   176x144     12      1 │     3.98MiB    60k https │ mp4v.20.3            mp4a.40.2       22k 144p
597 mp4   256x144     12        │     1.69MiB    25k https │ avc1.4d400b      25k video only          144p, mp4_dash
602 mp4   256x144     12        │ ~   5.38MiB    79k m3u8  │ vp09.00.10.08    79k video only
598 webm  256x144     12        │  1021.28KiB    15k https │ vp9              15k video only          144p, webm_dash
269 mp4   256x144     24        │ ~   8.53MiB   126k m3u8  │ avc1.4D400C     126k video only
160 mp4   256x144     24        │     1.62MiB    24k https │ avc1.4D400C      24k video only          144p, mp4_dash
603 mp4   256x144     24        │ ~  10.88MiB   160k m3u8  │ vp09.00.11.08   160k video only
278 webm  256x144     24        │     2.91MiB    44k https │ vp09.00.11.08    44k video only          144p, webm_dash
631 mp4   256x144     24 10     │ ~  12.51MiB   184k m3u8  │ vp09.02.11.10   184k video only
330 webm  256x144     24 10     │     4.79MiB    72k https │ vp09.02.11.10    72k video only          144p HDR, webm_dash
229 mp4   426x240     24        │ ~  13.70MiB   202k m3u8  │ avc1.4D4015     202k video only
133 mp4   426x240     24        │     3.19MiB    48k https │ avc1.4D4015      48k video only          240p, mp4_dash
604 mp4   426x240     24        │ ~  12.10MiB   178k m3u8  │ vp09.00.20.08   178k video only
242 webm  426x240     24        │     2.64MiB    40k https │ vp09.00.20.08    40k video only          240p, webm_dash
632 mp4   426x240     24 10     │ ~  18.28MiB   269k m3u8  │ vp09.02.21.10   269k video only
331 webm  426x240     24 10     │     7.70MiB   116k https │ vp09.02.21.10   116k video only          240p HDR, webm_dash
230 mp4   640x360     24        │ ~  26.57MiB   392k m3u8  │ avc1.4D401E     392k video only
134 mp4   640x360     24        │     5.98MiB    90k https │ avc1.4D401E      90k video only          360p, mp4_dash
18  mp4   640x360     24      2 │ ≈  14.88MiB   219k https │ avc1.42001E          mp4a.40.2       44k 360p
605 mp4   640x360     24        │ ~  26.13MiB   385k m3u8  │ vp09.00.21.08   385k video only
243 webm  640x360     24        │     5.46MiB    82k https │ vp09.00.21.08    82k video only          360p, webm_dash
633 mp4   640x360     24 10     │ ~  38.93MiB   574k m3u8  │ vp09.02.30.10   574k video only
332 webm  640x360     24 10     │    16.67MiB   251k https │ vp09.02.30.10   251k video only          360p HDR, webm_dash
231 mp4   854x480     24        │ ~  47.28MiB   697k m3u8  │ avc1.4D401E     697k video only
135 mp4   854x480     24        │    10.86MiB   164k https │ avc1.4D401E     164k video only          480p, mp4_dash
606 mp4   854x480     24        │ ~  36.65MiB   540k m3u8  │ vp09.00.30.08   540k video only
244 webm  854x480     24        │     8.68MiB   131k https │ vp09.00.30.08   131k video only          480p, webm_dash
634 mp4   854x480     24 10     │ ~  69.85MiB  1029k m3u8  │ vp09.02.31.10  1029k video only
333 webm  854x480     24 10     │    36.42MiB   549k https │ vp09.02.31.10   549k video only          480p HDR, webm_dash
22  mp4   1280x720    24      2 │ ≈  27.15MiB   400k https │ avc1.64001F          mp4a.40.2       44k 720p
232 mp4   1280x720    24        │ ~  83.63MiB  1232k m3u8  │ avc1.4D401F    1232k video only
136 mp4   1280x720    24        │    17.96MiB   271k https │ avc1.4D401F     271k video only          720p, mp4_dash
609 mp4   1280x720    24        │ ~  60.71MiB   894k m3u8  │ vp09.00.31.08   894k video only
247 webm  1280x720    24        │    16.06MiB   242k https │ vp09.00.31.08   242k video only          720p, webm_dash
635 mp4   1280x720    24 10     │ ~ 154.66MiB  2279k m3u8  │ vp09.02.40.10  2279k video only
334 webm  1280x720    24 10     │   104.02MiB  1569k https │ vp09.02.40.10  1569k video only          720p HDR, webm_dash
270 mp4   1920x1080   24        │ ~ 154.51MiB  2277k m3u8  │ avc1.640028    2277k video only
137 mp4   1920x1080   24        │    52.85MiB   797k https │ avc1.640028     797k video only          1080p, mp4_dash
614 mp4   1920x1080   24        │ ~ 104.93MiB  1546k m3u8  │ vp09.00.40.08  1546k video only
248 webm  1920x1080   24        │    30.68MiB   463k https │ vp09.00.40.08   463k video only          1080p, webm_dash
636 mp4   1920x1080   24 10     │ ~ 266.49MiB  3926k m3u8  │ vp09.02.41.10  3926k video only
335 webm  1920x1080   24 10     │   204.58MiB  3086k https │ vp09.02.41.10  3086k video only          1080p HDR, webm_dash
620 mp4   2560x1440   24        │ ~ 354.22MiB  5219k m3u8  │ vp09.00.50.08  5219k video only
271 webm  2560x1440   24        │   120.62MiB  1820k https │ vp09.00.50.08  1820k video only          1440p, webm_dash
639 mp4   2560x1440   24 10     │ ~ 721.96MiB 10637k m3u8  │ vp09.02.50.10 10637k video only
336 webm  2560x1440   24 10     │   640.46MiB  9661k https │ vp09.02.50.10  9661k video only          1440p HDR, webm_dash
625 mp4   3840x2160   24        │ ~   1.24GiB 18686k m3u8  │ vp09.00.50.08 18686k video only
313 webm  3840x2160   24        │   980.80MiB 14796k https │ vp09.00.50.08 14796k video only          2160p, webm_dash
642 mp4   3840x2160   24 10     │ ~   1.59GiB 23981k m3u8  │ vp09.02.51.10 23981k video only
337 webm  3840x2160   24 10     │     1.43GiB 22105k https │ vp09.02.51.10 22105k video only          2160p HDR, webm_dash
```

**Comment by ilikenwf** [comment]
Using my moderately awful plugin that ChatGPT largely put together, which wraps yt-dlp to stream whatever, HDR playback succeeds, albeit without audio:

https://github.com/ilikenwf/plugin.video.youtubedlstreamer

**Comment by garbear** [comment]
Cool to see an AI generated kodi add-on

**Comment by ilikenwf** [comment]
Yeah, I did it way back...I more or less directed it and pointed out python errors. For expedience, I just had it update for the xbmcvfs location change for translatepath, but it broke some parenthases and forgot an import...so I did that much...it actually is a handy tool. Thanks for that, though I guess you should thank the robot.

**Comment by CastagnaIT** [comment]
I have already warned you in your old issue,
you must respect our rules and you still ignore them

**Comment by ilikenwf** [comment]
Do you want me to verbatim copy and paste the entire issue from the main repo here? I mean I can and will.

**Comment by CastagnaIT** [comment]
no, you have to follow our template issue and provide all info that our template requires

**Comment by ilikenwf** [comment]
This is really tedious. It's not like nobody here doesn't already know what I'm discussing or talking about.

**Comment by CastagnaIT** [comment]
this is the way we work, the template exists for clear reasons needed for maintainers
you don't want to follow it, its fine... but it's not our problem anymore...

**Comment by ilikenwf** [comment]
I wonder how many things are broken that get ignored because of this bureaucracy. If I go back and revise this one can we recycle it or do I need to close it and make a new one?

**Comment by CastagnaIT** [comment]
> I wonder how many things are broken that get ignored because of this bureaucracy.

this is your judgment because you don't work behind this project and you don't know the intrinsic complexities

> If I go back and revise this one can we recycle it or do I need to close it and make a new one?

you can edit your first post by following our template text, this is the raw text
https://raw.githubusercontent.com/xbmc/inputstream.adaptive/Omega/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by garbear** [comment]
Indeed, @ilikenwf you mistake our technocracy for a bureaucracy. There is no ruling force, the innovators in the field lead the way for all of us in open source. The issue template is what they need.

**Comment by ilikenwf** [comment]
I've worked in open source before, I know this is necessary, I'm just sleepy and thus grumpy, please forgive me.

**Comment by garbear** [comment]
All forgiven. Continue being awesome.

**Comment by ilikenwf** [comment]
@CastagnaIT I have filled it in according to the template... I'm starting to think this is something to do with DASH/mpd since I can yt-dlp download the video, mux the audio and video into a 10 bit vp9 webm, and play perfectly...

So now the question is, whether this is an inputstream issue or if I need to close this and the kodi issue and open one at the Youtube or Intel repo instead...

**Comment by ilikenwf** [comment]
I figured out how to test with other resolutions supporting HDR, same results, sadly...

I still find it weird that having yt-dlp mux the hdr stream into a webm works...

**Comment by CastagnaIT** [comment]
thanks for the more clear info with template

now start to saying this
from what i remember youtube website has switched streaming from DASH to HLS
then you should play HLS streams not the DASH one

i dont know if the "youtube" addon has been updated for this website change, imo not yet,
since there are DASH HDR settings, but not HLS HDR settings?
and so this could be the reason that youtube addon is not able to get the expected quality list
you have to ask to "youtube" addon maintainers for details

in fact from the resolution list
of your comment above https://github.com/xbmc/inputstream.adaptive/issues/1410#issuecomment-1786549032
are "m3u8" that are referred to HLS, not DASH

from the log i dont see nothing relevant except of 
`error <general>: GetPicture - avcodec_receive_frame returned failure`
that however come from kodi core and i dont know what is referred

> If I use yt-dlp to get the raw URL for just the 4k HDR video, it will stream and play properly, albeit without audio

this is always referred to example video link provided?
however from the log i see that you are using an old ISA version

> info <general>: CAddonMgr::FindAddons: inputstream.adaptive v20.3.9 installed

the audio problem could be fixed on the last versions so please update to 20.3.13 or use Kodi 21 with last ISA 21.3.0

**Comment by matthuisman** [comment]
ive been working on a youtube replacement addon purely for playback of trailers without the login stuff

Here is the first version (slyguy repo needs to be installed first)
https://f.mjh.nz/.temp/plugin.video.youtube.zip

It will give you the quality pop-up
And can enable vp9 / av1 etc in the settings.

It implements the same addon ID and interface as the official youtube addon (WARNING: WILL REPLACE IT)
So a drop-in replacement to get trailers working etc

However, there are also some test streams if you run the plugin normally.
4k and 4k HDR

Hopefully this helps it make easier to select certain streams for testing / debugging.

**Comment by ilikenwf** [comment]
Oh cool - does it happen to have all the same other features as the default plugin?

**Comment by matthuisman** [comment]
no. its purely for taking a youtube ID and playing it. 
it implements the same paths as official, so any existing integrations should work with it
I just wanted my movie trailers to work well.

Has settings for auto quality select / which codecs to enable / disable.
Also on android - has a setting to use the Youtube Android app for playback.

**Comment by ilikenwf** [comment]
Interesting - I may play with it. I assume installing it would require removal of the official youtube client then?

Whatever logic you're using seems to be apparently superior to the official plugin at the moment for stream selection.

**Comment by matthuisman** [comment]
you can edit the plugin.py and just change the YT ids if you want to try with other streams etc :)

Yes. id backup the userdata for the official client.
Or, you can change the ID of this addon to something else and have both together.
Reason i use same ID is so the skin integration etc works.
Be great if Kodi some how abstracted away these hard-coded addon ids and made as a skin setting or something.
Same goes for the global search which i have a version for.

My plan is to have each of these drop-in replacement addons in there own repo. that repo lives in my repo.
That way, even if user has "enable updates from all repos" enabled - it wont pull in my versions from the main repo.
They would need to explicitly install the Youtube Drop-in repo to have it override the official

**Comment by CastagnaIT** [comment]
@matthuisman  your custom youtube addon make use of yt-dlp
but yt-dlp can provide the direct hls manifest urls that can be passed to ISA
without you have to construct custom manifest data

**Comment by ilikenwf** [comment]
The application itself or the API? Remember that addon is more an AI experiment than me tinkering, if it's the API, I'll have to argue with GPT until it makes it work to fetch the hls manifests instead...

**Comment by ilikenwf** [comment]
> you can edit the plugin.py and just change the YT ids if you want to try with other streams etc :)
> 
> Yes. id backup the userdata for the official client. Or, you can change the ID of this addon to something else and have both together. Reason i use same ID is so the skin integration etc works. Be great if Kodi some how abstracted away these hard-coded addon ids and made as a skin setting or something. Same goes for the global search which i have a version for.
> 
> My plan is to have each of these drop-in replacement addons in there own repo. that repo lives in my repo. That way, even if user has "enable updates from all repos" enabled - it wont pull in my versions from the main repo. They would need to explicitly install the Youtube Drop-in repo to have it override the official

So I changed the id, and the test videos...the HDR vp9 works...so this tells me that the stock youtube addon needs some updates/work.

**Comment by ilikenwf** [comment]
I suppose it could also be a case where because the official addon has to follow policies because of API use, it may be limited somehow.

**Comment by ilikenwf** [comment]
So MoojMidge has a test version of the youtube plugin for a future release, that unfortunately didn't fix this issue for me, but does allow me to play everything for the most part in 4k again, sans HDR...since the individual features are toggles now...

https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.2.2

**Comment by MoojMidge** [comment]
Thought I might clear up a few misunderstandings:

- The latest Youtube plugin has much improved stream extraction and selection functionality. You can enable whichever stream features you want via the settings. If you also enable `Settings > MPEG-DASH > Use MPEG-DASH for videos > Stream selection > Auto + Quality selection` then you can also change the selected streams on the fly using the InputStream.Adaptive stream selection dialog.
- The most common HDR format that Youtube provides are VP9.2 webm streams, with some AV1 MP4 streams as well.
- There are no MPEG-DASH or HLS manifests for these HDR streams. Enabling the use of HLS manifest will serve no purpose with regards to this issue.
- The MPEG-DASH manifests that are used are not provided by Youtube, they must be generated.
- The Youtube plugin has never needed a login to simply play a video, but it does need API keys to search for a video to play. If you construct a plugin url with the Youtube videoid e.g. `plugin://plugin.video.youtube/play/?video_id=VO8Bk03Xv90` then it will play that video without needing to search for it using the Youtube API.

@ilikenwf - Don't take this the wrong way, but you need to follow a more systematic approach to figure out what the problem is.

You are posting a lot of information but it is all largely meaningless because the information you are providing is a bit contradictory and when people ask you for a debug log or media info you don't seem very willing to provide any details.

The single debug log you have provided is for a 3840x2160@23.976 VP9.2 yuv420p10le video stream (~with correct HDR metadata~ with possibly incorrect HDR metadata, not sure if 0.0000 cd/m2 min luminance is valid, but all the other examples you mentioned had non-zero min luminance values) in a webm container, which didn't work.

You indicated there was at least one video played from the Youtube plugin using InputStream.Adative that did play properly, but haven't provided a debug log for that so it impossible to tell what type of video it actually was.

You also indicated that a sample video played locally also didn't work, but again no debug log.

The videos that you would have downloaded via yt-dlp are being remuxed and you say they work, but again no debug log so no one can see what the difference may be.

For what it's worth, the debug log you have provided shows that the video stream that didn't work with InputStream.Adaptive is the exact same video stream that does work when downloaded and remuxed, except that the framerate for the remuxed video is reported as 24 FPS rather than the original framerate of 23.976 FPS (but this may just be a media info issue).

I would recommend that you stick with the local files you have. Start by taking one that works and provide the media info and a debug log. Take the sample that was previously provided, which didn't work, and do the same. Maybe also confirm whether any video file that doesn't work in Kodi, does/doesn't also work in MPV.

Bringing InputStream.Adaptive, yt-dlp, and the Youtube plugin into the picture is just confusing things unnecessarily.

**Comment by ilikenwf** [comment]
I'll probably test with that vp9 that someone else posted when they had a similar issue and take the logs over to libva.

**Comment by MoojMidge** [comment]
@ilikenwf - Feel free to ignore me, but the main point that I was trying to get across, was that you should probably just stick with providing the required technical information in your original bug report https://github.com/xbmc/xbmc/issues/23957.

Rather than changing multiple things and reporting that something works, or doesn't work, without providing any other details, just make it as simple as possible for people to investigate and help you.

You don't need to create yet another bug report where people will have no idea what you are talking about, unless they try to dig through all of this other prior information that doesn't really clear anything up anyway.

[This video ](https://www.dropbox.com/scl/fi/v1z2qtglylts1y9dhnvh0/videoplayback.mkv?rlkey=y21b4fg6ar182rwyu0k21e3m3&dl=1) was provided. You said this doesn't work, so get a debug log showing this not working. Check if this works in mpv or ffmpeg directly.

In https://github.com/anxdpanic/plugin.video.youtube/issues/531 you said that `Obi-Wan - Obi-Wan vs Darth Vader - (HDR - 4K - 5.1) [VO8Bk03Xv90].mkv` that you downloaded using yt-dlp does work. You have provided media info for that file, but upload a sample of that file somewhere as well so people can test it. Get a debug log showing that this is working.

Both of these examples should use the exact same video stream from Youtube, and this should also be the exact same same stream that was in your original debug log, that didn't work using InputStream.Adaptive.

If one works but the other doesn't, from my laymans perspective this seems to indicate an issue with demuxing, but this seems highly improbable and is also not what is indicated by your log (not that I really know one way or another any way 😃).

Hopefully someone more knowledgeable in your original bug report can then provide some insight.
