### ISSUE TITLE
HLS live stream stops after several seconds in version 21.4.1

### ISSUE THREAD

**Issue by nirvana-7777** [peak3d/inputstream.adaptive#1438]
## Bug report
There seems to be a bug introduced with version 21.4.1 concerning playback of certain HLS streams. The stream starts but terminates after 10-60 seconds. With version 21.4.0 and the same configuration the same streams play without problems.
### Describe the bug

The stream is terminated and the last kodi screen appears. Streams of the same provider stop at different times but all within 1 minute.
The streams originate from a service provider in SEE. The streams are geoblocked and require a valid subscription. The addon which uses inputstream is a PVR addon. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected behaviour is that the stream plays the same way as in previous version like 21.4.0

## Actual Behavior

Instead the stream terminates without user interaction

## Possible Fix

Maybe the changes between 21.4.0 and 21.4.1 concerning HLS (I can see two in the changelog) could be reverted.

### To Reproduce

1. Start stream from service provider
2. Wait for the crash

### Debuglog

The debuglog can be found here:
A debug log of the issue is here:
https://paste.kodi.tv/ugacunumad

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
Will be provided  in comments

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Omega Beta
 - inputstream.adaptive version: 21.4.1

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
i have a theory but i i need you attach all m3u8 manifests to verify it

**Comment by nirvana-7777** [comment]
Manifests attached. Let me know if you need more examples.

[manifest_1703777826_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13788942/manifest_1703777826_child-video.txt)
[manifest_1703777821_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13788943/manifest_1703777821_child-video.txt)
[manifest_1703777816_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13788944/manifest_1703777816_child-video.txt)
[manifest_1703777816_master.txt](https://github.com/xbmc/inputstream.adaptive/files/13788945/manifest_1703777816_master.txt)

**Comment by CastagnaIT** [comment]
nope its not what i was thinking, its a regular live
from 21.4.1 PR's i dont see something that may affect this

i dont full understand your sentences,
above you have written:
> Instead the stream terminates without user interaction

and below:
> Wait for the crash

so i dont understand if there is a crash or simple stop playback or both

also from log seem you are using an unofficial kodi build "kodinerds" that is well known to introduce unexpected bugs,
so you should test with the last kodi nightly official build

**Comment by nirvana-7777** [comment]
Yes, that was not very clearly described. It's not a system crash. Just the stream is terminated.

I don't think that is has something to do with the Kodi version.
Reason a) Here: [https://forum.benchmark.rs/threads/eon-ex-d3go-za-eon-smart-tv-box-aplikaciju-postoji-posebna-tema.406427/page-300](url) is a bunch of people having the same issue. Maybe you can use Google Translate. And they are not having kodinerds builds for certain.
b) I can switch between 21.4.1 which always has the termination issues and 21.4.0 which doesn't have termination issues. That's what I meant with: without changing anything on the settings / configs etc except for the inputstream.adaptive version.

But I can surely also test on vanilla Kodi Omega Beta.

**Comment by CastagnaIT** [comment]
just to take note,
i found that also this free HLS stream seem to have similar problem
https://i.mjh.nz/PlutoTV/15f1aadf373bed3000794d1d7-alt.m3u8|user-agent=okhttp/4.9.0&x-forwarded-for=88.26.241.248
after more or less 1-2 minuts playback stop, so may be used to investigate
but so far i have not been able to figure out what stop the playback

**Comment by nirvana-7777** [comment]
I've tested again with another System, Linux this time. Just a "normal" Kodi Beta - no Kodinerds version.
Issue is again the same. Works with 21.4.0. Stream terminates with 21.4.1. So some change in between versions must break the stream.
Log here:
https://paste.kodi.tv/uharetoxis.kodi

On one stream I've waited some time without termination.

Manifests attached for both streams:
[manifest_1703877068_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13795669/manifest_1703877068_child-video.txt)
[manifest_1703877068_master.txt](https://github.com/xbmc/inputstream.adaptive/files/13795670/manifest_1703877068_master.txt)
[manifest_1703877073_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13795671/manifest_1703877073_child-video.txt)
[manifest_1703877078_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13795672/manifest_1703877078_child-video.txt)
[manifest_1703877085_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13795673/manifest_1703877085_child-video.txt)
[manifest_1703877090_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13795674/manifest_1703877090_child-video.txt)
[manifest_1703877095_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13795675/manifest_1703877095_child-video.txt)
[manifest_1703877100_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13795676/manifest_1703877100_child-video.txt)
[manifest_1703877105_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13795677/manifest_1703877105_child-video.txt)
[manifest_1703877110_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13795678/manifest_1703877110_child-video.txt)
[manifest_1703877115_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13795679/manifest_1703877115_child-video.txt)
[manifest_1703877120_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13795680/manifest_1703877120_child-video.txt)
[manifest_1703877126_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/13795681/manifest_1703877126_child-video.txt)

**Comment by CastagnaIT** [comment]
plaese try one of these test builds:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1444/1/artifacts
try at least 2 times to be sure, its just a test to know if depends from "[HLSTree] Dont overwrite interval value" commit
because sometimes with my test stream that i use take more time to stop and im not so sure of the results

**Comment by nirvana-7777** [comment]
The above provided version fixes the issue.
I've tested back and forth. Whenever I use the current version 21.4.1 from the repository the stream stops within 1-2 minutes. Whenever I've used the version above the stream runs through like in 21.4.0. Tested for 2 times 30 minutes.

Thanks for quickly providing the fix!

**Comment by CastagnaIT** [comment]
thanks for confirm
i have reverted a commit only to understand what happens, defitively this is not a fix
its needed investigate where come the root of problems

**Comment by nirvana-7777** [comment]
Let me know if I can assist in that.

**Comment by CastagnaIT** [comment]
i found something, there is something odd on this code:

https://github.com/xbmc/inputstream.adaptive/blob/8acd4c6ed53683a7b224bc9cf45c8b83bd526f17/src/common/AdaptiveStream.cpp#L810-L814

i always thought that it should be to update manifest at each new segment but seem its not so clear uses, not very understandable to me atm

our stream update manifest at defined intervals of time and the code above should not be executed, but was not so,
the commit https://github.com/xbmc/inputstream.adaptive/commit/545bd4ba15fed18cb2f91ab2e6b7c87f0f1fd655 has removed the `m_updateInterval = 0` on the top, that was forcing execute the code above in a "mixed" behaviours of manifest updates, the commit code modify `m_updateInterval` to 0 in a not so unsafe way because the value was immediately replaced with the right value

I still don't understand how this part works, it's quite a mess because it's all mixed up without clear and distinct functions in hls parser...

so now you can understand that reverting https://github.com/xbmc/inputstream.adaptive/commit/545bd4ba15fed18cb2f91ab2e6b7c87f0f1fd655 commit its not a solution, because this make works your stream but will break other streams due to this bad implemented code (clear example is my sample stream link that will have playback of DISCONTINUITY broken),
probably is needed to start by splitting all the code to try understand something
this will require many hours/days

**Comment by CastagnaIT** [comment]
after a new different investigation instead i found something else...
TSSampleReader set end of stream (m_eos) signal to true and stop the playback when waitingForSegment is false
https://github.com/xbmc/inputstream.adaptive/blob/2603755bcf8299472bfea12cafc692e3a6b1202b/src/samplereader/TSSampleReader.cpp#L86-L89

now this is what i understood:
- CTSSampleReader::ReadSample is called in async way by ReadSampleAsync from main.cpp by kodi often
- while do this an manifest update could happen at any time and waitingForSegment if was set to true, will be turned to false with this operation
- at this time new segments may not yet downloaded, and will not be downloaded until CTSSampleReader::ReadSample is called again (ReadSample will call AdaptiveStream::ensureSegment that run the downloads)
- meantime a new ReadSample call happens, but since there are no download data the ReadPacket fails, and waitingForSegment since has been switched to false TSSampleReader set the end of stream to true that stop the playback

this is the test fix:
https://github.com/CastagnaIT/inputstream.adaptive/commit/552699d101d6eda70382b2f37cac50f2bf26b4cb

and i can see that playback now works as expected
@glennguy imo the condition of mentioned source code above is wrong
i think that to set m_eos its needed that the code understand when there fails for a specific reason instead of check for waitingForSegment
EDIT: the check for waitingForSegment is used also on other demuxers, and so this could cause same side effect of stop playback also with all other types

**Comment by glennguy** [comment]
Ok here is what my understanding is.

The above code block makes sense to me. If we're in the 'waitforsegment' state, then the last period is still 'live' (doesn't have #EXT-X-ENDLIST tag yet) but we've run out of segments to download and rely on new manifest refreshes to provide new media segments. Therefore we don't set the end of stream flag.

>  its needed that the code understand when there fails for a specific reason

Perhaps but I don't think that would be the correct fix. The change proposed would work in this situation but I fear that the side effect is hanging streams in other cases. GetNextSample relies on EOS in its logic to determine the next sample reader to use.

So from your analysis above it sounds like a race condition on access/usage of waitForSegment value?

**Comment by CastagnaIT** [comment]
mmh maybe there is another way to solve this by keeping waitForSegment
i need to investigate better but related to this i found also another problem

with live stream this condition in prepareRepresentation is always false, so every time this method is called potentially always download the manifest also when should not
https://github.com/xbmc/inputstream.adaptive/blob/2603755bcf8299472bfea12cafc692e3a6b1202b/src/parser/HLSTree.cpp#L194-L196

prepareRepresentation method needs to be decoupled by its internal functions,
the download/parsing code and "update" current segment code,
as is is very chaothic difficult to understand, because this method is also called from different points

I'm trying to do this before i go on, because it's all too messy... at least to me makes things complex
I don't know if i will be able to make this code easier, but i will give it a try

**Comment by glennguy** [comment]
Thanks for all of your efforts as always!
Yes I brought in the code above because stream switching would always trigger a new playlist download for VOD. In hindsight it could have been named isDownloadedForVODOnly instead :)
My thoughts were then that it doesn't matter for live because if you're calling prepareRepresentation then you want a fresh copy always... but it sounds like you're thinking of cases where we should not.
Is another check needed to return early in the case of requesting a refresh too soon since the last (with exception to waitForSegment condition because I think we always want to try in that case)?

**Comment by CastagnaIT** [comment]
> My thoughts were then that it doesn't matter for live because if you're calling prepareRepresentation then you want a fresh copy always... but it sounds like you're thinking of cases where we should not

its about how manifest is updated:
1) per segment request
2) timed using worker

and so on `AdaptiveStream::ensureSegment` there are these two ways,
for the 1st case use RefreshSegments (internally always prepareRepresentation)
for the 2nd case use prepareRepresentation (called a bit below)
but the 2nd case must not download again the manifest, because has been already downloaded/processed by the worker

and...on this mess of things i think to have found another additional bug
so when you have "adaptive" to "selection stream" setting and the representation quality will be switched
playback stops seem because prepareRepresentation isnt called

**Comment by glennguy** [comment]
This 'additional bug' sounds suspicious. If stream is stopping 10-60 seconds after playback starts like in OP then is the original problem happening on rep change as well? In my experience in testing this happens regarding rep selection (but may have changed, I have not worked on this for some time)
* Playback is started with adaptive mode
* Initial representation is selected
* segment buffers start to fill with this rep 
* first segment is consumed by demux read calls. This can happen after the buffers are read or sometimes while they are still filling?
* at this point a new rep can be chosen

Any thoughts?

**Comment by CastagnaIT** [comment]
i managed how to get a a solution hoping its acceptable,
i also cleaned up a bit the code but not finished yet i need more time

**Comment by CastagnaIT** [comment]
If you want to test PR (kodi 21 only)
builds here: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1459/2/artifacts

**Comment by nirvana-7777** [comment]
I am happy to report that the streams which were previously causing the issue are working again with the above test version.
Thank you again for the great efforts you are putting into inputstream.adaptive!
