### ISSUE TITLE
Subtitles from Zattoo Channel "RTL" are not displayed corect in Kodi 21

### ISSUE THREAD

**Issue by werimail** [peak3d/inputstream.adaptive#1583]
### Describe the problem

The subtitles for the Zattoo (de) channel “RTL” are not displayed correctly. Only cryptic character strings are output.

### Debug log

[kodi.log](https://github.com/user-attachments/files/15871786/kodi.log)

### Stream manifest file(s)

[manifest_1718630702.txt](https://github.com/user-attachments/files/15871789/manifest_1718630702.txt)
[manifest_1718630706.txt](https://github.com/user-attachments/files/15871790/manifest_1718630706.txt)
[manifest_1718630707.txt](https://github.com/user-attachments/files/15871791/manifest_1718630707.txt)
[manifest_1718630711.txt](https://github.com/user-attachments/files/15871792/manifest_1718630711.txt)
[manifest_1718630712.txt](https://github.com/user-attachments/files/15871793/manifest_1718630712.txt)
[manifest_1718630716.txt](https://github.com/user-attachments/files/15871794/manifest_1718630716.txt)
[manifest_1718630717.txt](https://github.com/user-attachments/files/15871795/manifest_1718630717.txt)
[manifest_1718630719.txt](https://github.com/user-attachments/files/15871796/manifest_1718630719.txt)
[manifest_1718630721.txt](https://github.com/user-attachments/files/15871797/manifest_1718630721.txt)
[manifest_1718630722.txt](https://github.com/user-attachments/files/15871798/manifest_1718630722.txt)
[manifest_1718630724.txt](https://github.com/user-attachments/files/15871799/manifest_1718630724.txt)
[manifest_1718630726.txt](https://github.com/user-attachments/files/15871800/manifest_1718630726.txt)
[manifest_1718630729.txt](https://github.com/user-attachments/files/15871801/manifest_1718630729.txt)
[manifest_1718630732.txt](https://github.com/user-attachments/files/15871803/manifest_1718630732.txt)
[manifest_1718630734.txt](https://github.com/user-attachments/files/15871804/manifest_1718630734.txt)
[manifest_1718630737.txt](https://github.com/user-attachments/files/15871805/manifest_1718630737.txt)
[manifest_1718630739.txt](https://github.com/user-attachments/files/15871807/manifest_1718630739.txt)
[manifest_1718630741.txt](https://github.com/user-attachments/files/15871808/manifest_1718630741.txt)
[manifest_1718630744.txt](https://github.com/user-attachments/files/15871809/manifest_1718630744.txt)
[manifest_1718630746.txt](https://github.com/user-attachments/files/15871810/manifest_1718630746.txt)
[manifest_1718630749.txt](https://github.com/user-attachments/files/15871811/manifest_1718630749.txt)
[manifest_1718630751.txt](https://github.com/user-attachments/files/15871812/manifest_1718630751.txt)
[manifest_1718630752.txt](https://github.com/user-attachments/files/15871813/manifest_1718630752.txt)
[manifest_1718630754.txt](https://github.com/user-attachments/files/15871815/manifest_1718630754.txt)
[manifest_1718630756.txt](https://github.com/user-attachments/files/15871816/manifest_1718630756.txt)

### Additional info

https://github.com/xbmc/inputstream.adaptive/assets/88481706/8e1cf7f3-c7a7-4b2c-8022-a3503eabaddf
https://github.com/xbmc/inputstream.adaptive/assets/88481706/705044e8-5a36-4638-9b09-79f23a806f77
https://github.com/xbmc/inputstream.adaptive/assets/88481706/3c67acbb-8e21-45be-bf74-34fed74f6e50

### Operating system(s)

Windows

### Operating system version(s)

Windows 11

### InputStream Adaptive version(s)

21.4.9

### Kodi version(s)

Kodi 21 (Omega)

**Comment by CastagnaIT** [comment]
unfurnately im not able to play that stream from my country and that service is VPN protected
to try understand something you should provide:
1) a screenshot that show the "cryptic character" to show me the real meaning
2) download a couple of subtitle segment files and attach them here, they are embedded on mp4 so i need to inspect them
you can look at log in realtime and download them separately, i cant do it by myself by reading your log because since its a live they expire and i get only empty files

**Comment by werimail** [comment]
Apparently there is another provider problem here: Even in the original Samsung SmartTV app, the subtitles are not displayed correctly. I still have, for example, added a few segment files within the issue description (Additional info) above.

Greetings Weri

**Comment by CastagnaIT** [comment]
the second file 341090916-705044e8-5a36-4638-9b09-79f23a806f77
is the only one that have a kind of example

with a text of
`IMâ€œ`
if i force convert it to utf8 (with an utility not kodi) result as
`IM“`
but since text is not a complete sentence i have no idea what it means and if it could be correct or not (as is text looks a bit weird)
anyway i have no way to do this conversion since i tried load manually the file to ISA
and force load xml as utf8 but without success,
also tried to use `kodi::UnknownToUTF8` converter without success,
the text results always as `IMâ€œ`

maybe a possibility is try force change character set on:
kodi player settings -> subttiles -> Character set
its the only part of kodi that allow to force convert the text encoding but i think will fails since is similar to kodi::UnknownToUTF8 method

from my pov there is nothing that can be done
