### ISSUE TITLE
[Feature request] Ignoring Clearkey cenc check

### ISSUE THREAD

**Issue by alannl** [peak3d/inputstream.adaptive#1664]
### Describe the feature

Some streams run fine in Kodi using IS despite being identified as Sample-aes in the hls manifest.
The feature request: a kodiprop to skip this if-statement:
https://github.com/xbmc/inputstream.adaptive/blob/a7ef01d9fc2d56889a4901b0844ac60766368062/src/decrypters/clearkey/ClearKeyDecrypter.cpp#L43

### Motivation

To play video's and streams that use, or are defined with an unsupported encryption scheme but are working fine in Kodi with the IS cenc decrypter.

### Are you willing to contribute in development?

No

### Should a possible backport be considered?

No

**Comment by CastagnaIT** [comment]
no
if a stream is defined with cbcs encryption and currently there is no a cbcs clearkey decrypter implementation,
so its literally impossible make it to work now
then also no kodi props will be added to force your custom behaviour since has no sense

if you are talking about HLS
SAMPLE-AES == cbcs
SAMPLE-AES-CTR == cenc

if your manifest expose wrong encryption info you must fix your manifest by using a proxy

if your request is for a specific use case where before was working:
1) attach here all stream manifests, or,
2) if possible, provide sample stream so that i can test locally and verify better behaviours

**Comment by alannl** [comment]
I realize that  cbcs decryption isn't implemented. 
I changed the manifest as described in the disney+ thread to make the hls manifest compatible with WV, it's SAMPLE-AES and not SAMPLE-AES-CTR and didn't change it, I just tried it and was surprised that it worked, adding -CTR results in scrambled video.
I've send the stream url with key to you before. The KID is in the lic url of #ext-x-key, there's no KEYID var which should be added using proxy so Clearkey can detect it.

**Comment by CastagnaIT** [comment]
> I changed the manifest as described in the disney+ thread to make the hls manifest compatible with WV

no idea of what you are talking about
but D+ use by default widevine and i have always see only cenc's

> I've send the stream url with key to you before

from the PR, yes the sample you sent to me its different from D+,
its FairPlay DRM, and fwik FairPlay support only cbcs encryption
if you try force decoding that sample video as cenc will result in a broken malformed stream data, so cant be played

**Comment by alannl** [comment]
It plays, no deformation or errors, you should be able to replicate it.
Only the cenc check should be skipped and KEYID=0x{kid} should be provided using proxy so is-cc can parse KID from manifest.

**Comment by CastagnaIT** [comment]
tried dont works

**Comment by alannl** [comment]
Ok got it, thanks for trying. 
CWVCencSingleSampleDecrypter has no problem with the stream, I suppose it checks only for key system and not encryption method and fails when it sees skd, which changed to wv.
