### ISSUE TITLE
Is it possible to use this to create mp4s?

### ISSUE THREAD

**Issue by bfayers** [peak3d/inputstream.adaptive#172]
Say I happen to have some mp4 files that are encrypted with wv can I use this to create another mp4 file that is decrypted?

**Comment by FloridaStream** [comment]
@bfayers this is just for watch, decrypt never will be supported by inpuststream.adaptive.
peak3d already say this. 👌

**Comment by basrieter** [comment]
@bfayers the way you state your question, we could be tempted to think you would be using this for less legal activities. If so, I would not post these questions here.

**Comment by bfayers** [comment]
@basrieter Hi!
I don't think it's illegal activites? I own some videos on youtube (films) that i paid for but if i use youtube-dl for them it downloads the full length but is encrypted, with presumably WV

**Comment by peak3d** [comment]
@bfayers for offline watching widevine supports OFFLINE keys.
The correct way - for offline - is implementing an offline key store in inputstream.adaptive, and store the files encrypted.

Storing decrypted streams on (hopefully) your storage is not the correct way.

If ppl. try to go this way, content providers will restrict more to avoid this -> more development for me.

because of that no support on this topic here, sry.
