### ISSUE TITLE
Error: Unable to load widevine shared library

### ISSUE THREAD

**Issue by mrfixit2001** [peak3d/inputstream.adaptive#175]
I am using the following commits in a custom buildroot build:
Kodi Leia: b02d4308304f991c01cc2a69833e2642f19786d1
InputStream: 16a4043a8f4a98f51e23c0e440773478fabe30b1
Kodi-Platform: e8574b883ffa2131f2eeb96ff3724d60b21130f7

I start kodi, enable inputstream, enable netflix, login to netflix, and can then browse my list just fine.

When trying to play anything on netflix, I receive the following error:
ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library

Here is the full debug log: https://pastebin.com/Tnuci1pJ

For troubleshooting, you'll see that I updated line 426 of wvdecrypter.cpp to include strBasePath in the log to provide as much detail as I could, otherwise no modifications were made to the addon.

I have confirmed that the newest version of libwidevinecdm.so was installed by inputstreamhelper and does exist in the path listed in the log. I have confirmed that all permissions are correct on that folder (everything on the system runs as root). And I have confirmed that the basepath was successfully created by the addon, however the folder is empty.

Please let me know next steps, I'm happy to provide further logs.

I'm thinking I need to determine which one of these is causing the error, media::CdmAdapter() or media::CdmConfig(). Would appreciate any and all assistance.

**Comment by peak3d** [comment]
try ldd [path_to_libwidevine]/libwidevine.so if there are dependencies missing.

**Comment by peak3d** [comment]
No idea about the python issue, really.
But your license fails because of this.

`03:17:48.725 T:3772240848   DEBUG: [Netflix] Error getting license: {"result": {"errorDetails": "No Details Available", "errorSubCode": 1331, "errorExternalCode": "P7", "errorDisplayMessage": "", "errorEdgeCode": 3057, "data": {"CODE": 3057, "ERROR_NAME": "ModelDeviceMismatch", "DRM_LICENSE_TYPE": "standard", "REQUEST_CONTEXT_COUNTRY": "US", "REQUEST_CONTEXT_APP_ID": 0, "CLIENT_RETRYABLE": "false", "LOCAL_MESSAGE": "Model device mismatch", "REQUEST_CONTEXT_ESN": "NFCDCH-LX-ENMW3UGR7DT2NKGUPGT70Y8J0V02MY", "REQUEST_CONTEXT_STACK": "prod", "REQUEST_CONTEXT_DEVICE_TYPE_ID": 1223, "SUCCESS": false, "ROOT_CAUSE_STACK_TRACE": "Not available.", "REQUEST_CONTEXT_CLIENT_ID": "cd8d8cec-c31d-4468-95e0-40e19028ffc8", "REQUEST_CONTEXT_ENVIRONMENT": "prod", "DESCRIPTION": "com.netflix.pbl.error.PblException: Model device mismatch\n\tat `

You should check your ESN,maybe remove it from settings and let it evaluate automatically.

**Comment by mrfixit2001** [comment]
Good catch. I cleared the ESN from settings but unfortunately it continued to return the same errors.

The "Model device mismatch" has me wondering. I'm guessing that if this first error is fixed the python error goes away because the value it's looking for is correctly passed. So let's concentrate on this one. 

How is the ESN currently auto-calculated and what might cause this message?

**Comment by peak3d** [comment]
For != android it's taken from browser (could be issues with the UA)
If possible on your device, install chrome / chromium, start netflix and grep in sources for the ESN.

For android it is evaluated from system properties.

Reason2 could be that you use a libwidevine for a device which has special restrictions.

But all these questions are Netflix related and OT to inputstream.adaptive addon.

**Comment by mrfixit2001** [comment]
This is linux and not android, and netflix is being launched from kodi (no browser). The environment is GBM without X and without Wayland, so Chromium is not an easy one to install.

The device itself is a Rock64 from Pine64, so there shouldn't be any special restrictions, and I can confirm that netflix did used to work back about 6 months ago when I had tested it from LibreELEC. 

I realize these questions are Netflix specific, and I appreciate you responding, because they have been very unresponsive on their repo issues.

Is it possible for me to use an ESN from another device? Or is there a way for me to manually determine what it should be?

**Comment by peak3d** [comment]
You should be able to use an ESN from another arm32 device where it is running, yes.

FYI: There is also information in libwidevine which is passed on license request to the license server.
Because of that I didn't say tht your device / os has restrictions, but maybe the libwidevine itself.

Fact is, that the libwidevine must match to the ESN, so you have 2 pieces to play around with.
Good luck!

**Comment by mrfixit2001** [comment]
So I am unable to change my ESN manually. The license request error still always shows the old ESN even after I update it and restart KODI. When I go back into netflix settings it shows the custom ESN that I entered, but the original ESN continues to be referenced in the log and attempts continue to fail. 

My running theory is that the helper is installing the wrong widevine, any thoughts on how to validate which one is the *correct* selection from this list? https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.conf

I've confirmed by adding logging into inputstreamhelper that it's now identifying me as 'arm', and it's installing: chromeos_10575.58.0_daisy-spring_recovery_stable-channel_spring-mp-v3.bin
but I have no idea if that's the correct selection.

Once again, I know you're helping me debug someone's elses addon, it's truly appreciated because they have been unresponsive at both asciidisco and emilsvennesson.

**Comment by peak3d** [comment]
Netflix addon displays always the evaluated ESN in kodi log but this does not mean that it uses it.
There is a log line in kodi log where the profiles are loaded and this line shows the real ESN which is used.

You should be able to find the log line if you search for the one you put in settings by searching the log for it.

Pls. provide a new log file, maybe I can find something.

**Comment by mrfixit2001** [comment]
Thanks again for the time you're taking to review. I deleted widevine and let it download again so you could see the full log of the entire process. It's too long for one pastebin so I had to split it into two.
Here's the log:
Part 1 - https://pastebin.com/cAZSTLY4
Part 2 - https://pastebin.com/dNdSzpB9

You might see a few extra unfamiliar log lines that I've added here and there when debugging, just fyi.

**Comment by mrfixit2001** [comment]
Closing and reopening because the log has changed in the newest netflix version
