### ISSUE TITLE
Time changes to GMT after starting DASH Livestream (Youtube/DAZN)

### ISSUE THREAD

**Issue by greystashh** [peak3d/inputstream.adaptive#187]
I recognised an issue concerning the kodi clock after starting DASH live streams. The clock will always be set to GMT (minus two hours from CEST) after I started a stream with dazn add-on or select YouTube live streams. YouTube vod doesn't have this neither HLS live streams (Eurosportplayer).

My system is Android Oreo on Shield with latest firmware and Kodi 18 beta2. Besides I am using a tvheadend PVR which make this clock switch a bit annoying if I have to restart kodi to solve this again.

Anyone experiencing this too and would it be able to fix it?

**Comment by anxdpanic** [comment]
For the YouTube add-on at least, this seems to be caused by availabilityStartTime and has only been reported for Android 

Was reported with add-on generated VOD manifests-was inadvertently left in the manifest-, removing availabilityStartTime solved the issue for the generated manifests.

Example YouTube Live manifest: https://pastebin.com/gp4VA7Fx

**Comment by JinRonin** [comment]
@anxdpanic
This has been fixed with https://github.com/peak3d/inputstream.adaptive/commit/8cdc2552ed8e24e13bc61ab5b7e9d0a3e03bc829
