### ISSUE TITLE
Auto stream selection always chooses 720p for 1080p Youtube streams

### ISSUE THREAD

**Issue by mooninite** [peak3d/inputstream.adaptive#237]
Fedora 29
InputStream Adaptive 2.3.12

Youtube streams are always choosing 720p even though 1080p is available.

Example video: https://www.youtube.com/watch?v=UA3jI71gy8E
720p60 is always chosen with "Auto" but using "Manual" I can choose the 1080p60 stream and it plays fine.

Netflix streams always pick 1080p with "Auto" set and play fine.

Debug log from playing example video using "Auto": https://gist.github.com/mooninite/90d5b30821a80f13db41cbdc4b68c941
MPD of example video: https://gist.github.com/mooninite/1864f7ccd2e08d1247f14383b2ce48f2

**Comment by fragande** [comment]
What does your InputStream Adaptive settings look like? For me the problem turned out the be that "Max. Resolution general/secure decoder" was set to 1080p. For some reason this makes the videos play in 720p. When set to "Max" they play in 1080p. Also paired with "Min. Bandwidth" set to 30.000.000, but I'm not sure that's needed.

**Comment by mooninite** [comment]
Thanks for the suggestion. I did have 1080p set and changing to Max fixed it. 1080p for both YouTube and Netflix.

**Comment by dagwieers** [comment]
We have a similar problem with our plugin. We cannot get 720p when **InputStream Adaptive** has **Max. Resolution general decoder** set to 720p. We can only get 720p streams when it is being set to 1080p.

More information at: https://github.com/pietje666/plugin.video.vrt.nu/issues/195
