### ISSUE TITLE
error version widevine

### ISSUE THREAD

**Issue by snock** [peak3d/inputstream.adaptive#321]
I use archlinux arm with raspberry 3b +. When I install / update the addons. I always get that you have to update widevine ... If I give it in the end it gives error.

I download the latest version libwidevinecdm.so from blog.vpetkov.net.

The only way I found was to put:

> def _check_widevine(self):                                                                                               
>         **return True**   <---

**Comment by dagwieers** [comment]
@snock You can disable **InputStream Helper** in the add-on settings for the time being. This will have the same effect as your patch.

But in order to understand what is happening we would not a debug log (with the add-on enabled) and it could help if you make a screenshot of the **InputStream Helper information** pane (also from the settings).
