### ISSUE TITLE
Please clarify the stream selection: Manual video option string

### ISSUE THREAD

**Issue by john-tho** [peak3d/inputstream.adaptive#443]
In playing a video, I want the most suitable (to my other settings) stream selected, but with the ability to also select a different stream during playback. I would pick a setting name for this as something like:
- _Auto with video override_
- _Auto with video selection_
- _Manual with auto video selection_

_Manual video_ (c2c187bff4f1b25b84e09383401aa3409182531b) does this, after 87d4c4629e9ec408d7e5d231ec1a67fcb7cf6411 fixed a typo? (2.5.6-Matrix, 2.4.3-Leia)

I only found this through trial and error in Kodi. It seemed for `STREAMSELECTION`:
- _Auto_ did not allow any stream selection
- _Manual_ selected the first stream
  I gave up here until I looked at the source…
- _Manual video_ selected the most suitable stream as default, but also allowed stream selection.

Setting in question:
https://github.com/peak3d/inputstream.adaptive/blob/0d3bd30511c53003b96e01611c20c1e885ef6d65/inputstream.adaptive/resources/language/resource.language.en_gb/strings.po#L112

Apologies for the trivial issue, and not indicating that my terminology is the best, but the existing could be improved to indicate the sensible default is selected?

Otherwise, the software works brilliantly for me, thank you very much.

Cheers

**Comment by CastagnaIT** [comment]
i do not full understand how the code of _manual_ option works
but this is what Peak3d say to me long time ago:

> This is what "manual" is doing: provide every representation to kodi.

referred to dash representations

then if the numbers of streams representations exceede the Kodi limits, Kodi will cause a lack of streams

the kodi limits on Kodi <= 18.x is of 32 total streams
the kodi limits on Kodi >= 19.x is of 256 total streams

For example:
on Kodi 18.x if the user enable the "manual" option will accuse missing of audio/subtitle languages,
this because of too streams passed to Kodi example:
10 video streams
10 audio/subtitle languages
-for every audio streams 5 bandwidths and 2 type of channels
-for every subtitle normal and forced stream type

This will results in a:
10 video streams
100 audio streams
20 subtitle streams
Total of 130 streams

exceed Kodi <=18.x limits and this is a problem

but there are side effects:
- on audio selections window, all audio streams have same name, the final user do not understand why
- the auto audio language selection of kodi works bad, selects the first stream in language, but there is no distinction with bandwidth

for a novice user your suggestion is not very understandable
I would rather write something about debugging or warning for "manual" mode
the manual option should never be used as normal playback option

example:

original -> changed
- Auto -> Auto (seem more appropriate leave it as is)
- Manual video -> Auto - Allow video stream selection
- Manual -> Manual for debugging

**Comment by john-tho** [comment]
Yes, _Auto - Allow video stream selection_ makes sense.
I was only suggesting changing _Manual video_, and provided the different suggestions for that one setting.

**Comment by CastagnaIT** [comment]
if the mainteiner agree will be possible changing text

**Comment by glennguy** [comment]
@CastagnaIT thanks for the detailed explanation, I wondered why that setting came to be! Maybe we should look at adding some of this information to the wiki

**Comment by CastagnaIT** [comment]
yes we could add a new wiki page as "add-on settings"
where to explain all settings

**Comment by peak3d** [comment]
I'm fine with renaming @CastagnaIT

**Comment by CastagnaIT** [comment]
@dagwieers can you give your opinion on the new descriptions I've proposed?
the goal is to simplify interpretation for the inexperienced user

original -> changed

- Auto -> Auto
- Manual video -> Auto - Allow video stream selection
- Manual -> Manual for debugging

if that's all right, I'll do PR

**Comment by dagwieers** [comment]
@CastagnaIT I am honoured you pick me for making a call, but I don't think I am entitled. @peak3d already decided this for us. :wink: 

But since you asked for my opinion, I think we should not indicate what people ought to use it for (although I understand that it is not practical unless for debugging). I would rather go for:

- Automatically select streams
- Manually select video stream
- Manually select all streams

I think this gives the most context, and leave it up to people what they prefer regardless of use-case.

If **inputstream.adaptive** would move to the new settings.xml format, we could add help text for each setting where we can provide more context. Personally I am all for that (unfortunately the new settings format does not offer all functionality as the original settings.xml)

**Comment by CastagnaIT** [comment]
i close this issue since in Nexus the settings has been reworked in full
