### ISSUE TITLE
Tuning of maximum bitrate for DRM and non-DRM video separately?

### ISSUE THREAD

**Issue by Harvie** [peak3d/inputstream.adaptive#527]
This menu contains separate settings for DRM (secure) and non-DRM maximum resolution.
Can you please also add separate settings for DRM and non-DRM min/max bitrate? (currently the bitrate setting is common for drm and non-drm).
My raspberry pi has troubles with decoding high bitrate 1280p DRM video, but can decode both low bitrate 1280p DRM video and high bitrate 1920p  non-DRM video.

![image](https://user-images.githubusercontent.com/276504/95779825-12e7af00-0ccb-11eb-9f38-68383cd84c1f.png)

**Comment by CastagnaIT** [comment]
Try read wiki: https://github.com/peak3d/inputstream.adaptive/wiki/Settings

**Comment by Harvie** [comment]
> Try read wiki: https://github.com/peak3d/inputstream.adaptive/wiki/Settings

@CastagnaIT How that will help me? Issue remains the same after reading the wiki. Can only set separate resolutions, not the bitrates.

**Comment by CastagnaIT** [comment]
we have discussed your request internally
but here we are talking to add new settings workarounds

as you have already stated we already provide a max resolution settings workaround (DRM / non-DRM)
to help users to try contain the problem on devices with low-end CPU's

but any new workaround setting cannot solve the problem at root
because when the CPU will be highly load also for other operations will result in a stuttering video
which depends not only on the bitrate/resolution but also on the type of video codec

so we prefer to find a way of lowering the quality according to CPU load
feature to be implemented in the future

for the time being it will have to adapt to using the existing settings
