### ISSUE TITLE
[MPD] Support multiple video AdaptationSet (urn:mpeg:dash:adaptation-set-switching:2016)

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#555]
Seeing a few mpds that have multiple video AdaptationSet.
eg.
```
<AdaptationSet id="9" group="2" contentType="video" mimeType="video/mp4"....>
        .............
       <SupplementalProperty schemeIdUri="urn:mpeg:dash:adaptation-set-switching:2016" value="10"/>
</AdaptationSet>
<AdaptationSet id="10" group="2" contentType="video" mimeType="video/mp4"....>
        .............
       <SupplementalProperty schemeIdUri="urn:mpeg:dash:adaptation-set-switching:2016" value="9"/>
</AdaptationSet>
```
maybe could be incorporated into new adaptive bitrate switching code by @spyderboy92

my current work around uses a proxy to move which ever adaption set has highest qualities to the top so IA uses that.

**Comment by kszaq** [comment]
Hi @matthuisman. I am trying to work around the same issue: I have MPD with multiple video adaptation sets and IA does not respect resolution/bandwidth limits, IA works like it is forcing manual stream selection. Can you possibly point me to the addon where you're proxying results so that I can c/p your workaround? Thank you in advance!

Edit: Found it in HBO Max addon. 👍

**Comment by kszaq** [comment]
Since I'm a Python noob, I have added an ugly workaround in IA:
https://github.com/kszaq/inputstream.adaptive/commit/3eaa462fa9f67d9da80297d4333a32d58457f154

But this may not work in case video AdaptationSets have different parameters. In my case they are identical, so it's safe to merge Representations into one AS.

**Comment by CastagnaIT** [comment]
Someone can provide a manifest for this use case? HBO Max?
