### ISSUE TITLE
Live HLS (with DRM) streams (resync) issue 

### ISSUE THREAD

**Issue by ivankokan** [peak3d/inputstream.adaptive#584]
Hi, We have trouble opening live HLS streams (with DRM) in NBA Kodi add-on. Sometimes it opens at the very beginning, sometimes somewhere in the middle, and sometimes correctly (truly live, this apparently happens at 2 am UTC onwards - what?).

Here is the log file
[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/5762560/kodi.log)
and here is how we utilize the IS.A with ISH:
https://github.com/ivankokan/xbmc.plugin.video.nba/blob/b558a05cfc62ecac71e137a504c87c9f61dec0e2/src/common.py.

Is there any parameter to use in order to resolve the issue?

**Comment by glennguy** [comment]
Hey @ivankokan it sounds likely that the playlist has #EXT-X-DISCONTINUITY tags, could you attach one of the variant m3u8 files? eg. https://lion-nba-msl.akamaized.net/cmaf/live/2022959/nlds/nba/akmsl/drm/cmaf/wvpr/mem/as/live/nlncp/0022000087-b/br_6000_video/br_6000_long_fmp4Video.m3u8

edit: might also be useful to have both video and audio m3u8s, as there also seems to be issues from your users with audio missing??

**Comment by ivankokan** [comment]
> Hey @ivankokan it sounds likely that the playlist has #EXT-X-DISCONTINUITY tags, could you attach one of the variant m3u8 files? eg. https://lion-nba-msl.akamaized.net/cmaf/live/2022959/nlds/nba/akmsl/drm/cmaf/wvpr/mem/as/live/nlncp/0022000087-b/br_6000_video/br_6000_long_fmp4Video.m3u8
> 
> edit: might also be useful to have both video and audio m3u8s, as there also seems to be issues from your users with audio missing??

Here are two resources I just generated (but had no video syncing issues now & I have no audio issues on this device at all).

[m3u8s.zip](https://github.com/peak3d/inputstream.adaptive/files/5762926/m3u8s.zip)

**Comment by ivankokan** [comment]
@glennguy Here is a set for the non-working live stream (**it started and choked at the very beginning, did not sync live**). I downloaded several m3u8 resources mentioned within the kodi.log, almost 20 out of 55, among which many are duplicates. (I did not pay attention to what is really written in the log, I just downloaded them one by one...)

[around 0-30, not working.zip](https://github.com/peak3d/inputstream.adaptive/files/5767448/around.0-30.not.working.zip)

**Comment by ivankokan** [comment]
@peak3d @glennguy Do you, at least, have any idea what to investigate here?

**Comment by glennguy** [comment]
Hey @ivankokan I'll get back to you later today after work :)

**Comment by glennguy** [comment]
@ivankokan
There's a few things going on here, I'll try to explain and give some solutions/workarounds.

There are indeed discontinuities in these playlists, eg.:
```
#EXTINF:5.989316,
br_3000_audio-268300795.mp4
#EXTINF:6.006000,
br_3000_audio-268300796.mp4
#EXTINF:6.006000,
br_3000_audio-268300797.mp4
#EXTINF:5.989317,
br_3000_audio-268300798.mp4
#EXTINF:6.006000,
br_3000_audio-268300799.mp4
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2021-01-05T00:00:02.521Z
#EXT-X-KEY:METHOD=SAMPLE-AES-CTR,URI="data:text/plain;base64,AAAASHBzc2gBAAAA7e+LqXnWSs6jyCfc1R0h7QAAAAEyyl/krD9wxVl0iO5XjeHYAAAAFAgBEhAyyl/krD9wxVl0iO5XjeHY",KEYID=0x32CA5FE4AC3F70C5597488EE578DE1D8,KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed",KEYFORMATVERSIONS="1"
#EXT-X-KEY:METHOD=SAMPLE-AES-CTR,KEYFORMAT="com.microsoft.playready",KEYFORMATVERSIONS="1",URI="data:text/plain;charset=UTF-16;base64,AAACeHBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAlhYAgAAAQABAE4CPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgA1AEYALwBLAE0AagArAHMAeABYAEIAWgBkAEkAagB1AFYANAAzAGgAMgBBAD0APQA8AC8ASwBJAEQAPgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwBwAGwAYQB5AHIAZQBhAGQAeQAuAGQAaQByAGUAYwB0AHQAYQBwAHMALgBuAGUAdAAvAHAAcgAvAHMAdgBjAC8AcgBpAGcAaAB0AHMAbQBhAG4AYQBnAGUAcgAuAGEAcwBtAHgAPAAvAEwAQQBfAFUAUgBMAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA="
#EXTINF:6.006000,
br_3000_audio-268300800.mp4
#EXTINF:5.989317,
br_3000_audio-268300801.mp4
#EXTINF:6.006000,
br_3000_audio-268300802.mp4
#EXTINF:6.006000,
br_3000_audio-268300803.mp4
```

 The `#EXT-X-DISCONTINUITY` tag is to signal the player that it will need to reset/reinitialize as the next segment is from a separate video file (at least in theory) with potentially different codec profile, resolution etc. Usually used to insert ads, or if the encoder on the backend has had to restart for whatever reason. IA/Kodi handles this by splitting the sections between each discontinuity into periods (IA) / chapters (Kodi). This works well for static/non-live playlists in Leia and Matrix. 

Live HLS playlists with discontinuities (contains `EXT-X-DISCONTINUITY-SEQUENCE` tag) though are a different issue...
They are supported in Matrix (IA >= 2.6.1) but the changes weren't backported to Leia.
A backport could be prepared but it would require some motivation from peak3d to make a release. Leia is now finalized so a new release of IA for Leia would require adding IA/Android builds to the official repo (atm IA is 'baked in' to the apk) plus appropriate changes within IA.

With regards to the video not starting at the live edge:
This will happen when there is more than one chapter/period (at least one discontinuity in hls playlist) - it will start ~12 seconds from the end of the first chapter.
It may be easy-ish to fix for DASH videos however for HLS it is non trivial due to the workflow. From memory: with HLS, IA is unaware of how many chapters there are at the time control goes back to Kodi (master playlist is read/parsed but variant streams are yet to be) so we can't know which chapter to ask for Kodi to seek to. Maybe there is an easy 'hack' to make it happen but a proper solution is the only way forward. As there is a rewrite in progress (including segment buffering and adaptive switching) which touches a lot of code, the fix for this issue is probably best to wait until afterwards IMO.

There is a workaround that you could try from the add-on's end:
At least in this example the same widevine key/pssh is used, and looking at the segment names it would seem that there isn't actually a discontinuity in this stream - the segment numbers are continuous. As well as that we are still using the same initialization mp4. Knowing this you could use a proxy server service in the add-on to rewrite the m3u8 playlists, removing the discontinuity tag and adjacent EXT-X-KEY tags. You would then have a 1 period/chapter playist(s) and these issues should disappear. 

@matthuisman did you end up with a viable workaround other than the above for getting streams to start at the live edge?

**Comment by scottydulton** [comment]
Thankyou @glennguy, this is something!

**Comment by ivankokan** [comment]
@glennguy Let me check if I got your analysis right?
- There should be no issues on Kodi Matrix but our add-on is not Matrix-compatible (yet).
- In order to have HLS live working on Kodi Leia, we should implement the proxy service the way you described above (it is not expected to have improvements/fixes implemented for Matrix backported to Leia).

Considering that many users are still using Leia (and will continue using it for some significant time), I will try to address the proxy idea first (but also make our add-on Matrix-compatible in parallel).

**Comment by glennguy** [comment]
That's right, I think you'll have success with the proxy idea. Not the most ideal solution but it should work.

Matrix RC1 is just around the corner (only a matter of days now) so I think you'll find the adoption should accelerate a lot from now (and the associated cries for you to make a compatible add-on)
