### ISSUE TITLE
[HLS] URI="/path/" fails (regression)

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#591]
Works fine in 2.4.6.
Fails in 2.6.6

`#EXT-X-KEY:METHOD=AES-128,URI="/nlds_vod/csmrugby/vod/2021/01/16/8563/whole/v1/stream/2_8563_edinburgh_glasgow_2016_b_whole_1_4500.mp4/000000.m3u8.key?hdntl=exp=1611043963`

Correct URL (2.4.6. works):
`https://neuclnlds1620oc.akamaized.net/nlds_vod/csmrugby/vod/2021/01/16/8563/whole/v1/stream/2_8563_edinburgh_glasgow_2016_b_whole_1_4500.mp4/000000.m3u8.key?hdntl=exp=161104396`

2.6.6 errors with
` AddOnLog: inputstream.adaptive: Cannot download /nlds_vod/csmrugby/vod/2021/01/16/8563/whole/v1/stream/2_8563_edinburgh_glasgow_2016_b_whole_1_4500.mp4/000000.m3u8.key?hdntl=exp=1611043963`

So appears it isn't appending the base url for urls starting with /
Relative paths (../../../) work fine when I tested

**Comment by kyl416** [comment]
Is this still an issue with Matrix? I had the same issue with another stream when the related commits were backported to the Leia branch and tracked down which one caused it to break:
https://github.com/xbmc/inputstream.adaptive/issues/531#issuecomment-743690053

For me it mostly affected streams powered by a streaming platform based in Japan, who's kind of like Japan's answer to ThePlatform and power the global players for several of their sports leagues. If the issue is also affecting streams from a major provider like Endeavor (Neulion), it has the potential to be a showstopper for some sports addons since they power the streaming players for several sports leagues and networks in North America and Europe.

Luckily those commits never made it to a release version on Leia, but if the issue is still there with Matrix, I'm going to have to hold on upgrading until it's fixed.

**Comment by matthuisman** [comment]
Is still issue in Matrix (2.6.6)
I can probably PR a fix for this though :)

**Comment by matthuisman** [comment]
the below can be saved to a .strm file to test in kodi

```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
https://raw.githubusercontent.com/matthuisman/ia_tests/master/hls_uri_slash/master.m3u8
```

and confirmed the bug is introduced here:
https://github.com/xbmc/inputstream.adaptive/commit/34c218540b6278b5d7fd7d4bf5cac01b28998183

Seems base_domain_  isn't being set

**Comment by matthuisman** [comment]
@kyl416
PR for fix here:
https://github.com/xbmc/inputstream.adaptive/pull/607

**Comment by kyl416** [comment]
Thanks for the quick fix, unfortunately I won't be updating to Matrix anytime soon to test it though because of a much bigger issue involving nearly every add-on missing from the official repository on Android devices:
https://forum.kodi.tv/showthread.php?tid=360782

Luckily I only updated my lesser used Tablet and not my main Shield since it's impossible to revert to Leia on Android without wiping all the data and custom settings. Plus because of how inputstream.adaptive is bundled, my Android devices wouldn't even see the fix until they release a new version of the app.

**Comment by kyl416** [comment]
I just tested a build with that fix, and can confirm it fixed the issues with my streams.
