### ISSUE TITLE
Support for WV Offline Storage possible?

### ISSUE THREAD

**Issue by yoshimo** [peak3d/inputstream.adaptive#595]
Various providers, Amazon and Netflix for example allow you to download episodes and movies and watch them offline for a while.
This would help with mobile data plans and allow higher resolution for people with low bandwith.
It would be great if IA would eventually support this.

**Comment by CastagnaIT** [comment]
I think that ask this type of feature is too premature due to the current state of development of ISA that still needed developments and optimizations in different areas, and a kind of this type need to be also supported by an addons e.g. to handle the temporary linceses, data expiring, manage audio/video/subtitles files, etc... so a certain amount of cooperation is needed between addons devs and Kodi Team which i currently find difficult to see for this specific type of request

if, on the other hand, your request is a proposal to help add this feature by providing a development collaboration on its implementation with a specific addon, then things could perhaps have a better outcome

speaking as far as i am concerned with Netf**x, seems can be done with PlayReady only, the support for this DRM is not implemented on all plaforms supported by ISA, and in the addon currently lacks PlayReady support completely, so at the moment it is unthinkable to even think about it.

@glennguy IMO I don't think this issue will be evaluated in the near future, so this issue could be closed
