### ISSUE TITLE
Cannot find the "InputStream Adaptive" extension

### ISSUE THREAD

**Issue by Benj0B** [peak3d/inputstream.adaptive#600]
Hello,

I want to watch streaming streams through Kodi software, which I installed on my Raspberry Pi 4.
For example, with the Disney + extension, I followed the tutorials found on the internet.
No worries for this point. I manage to connect to it, to navigate in their menu, but when launching a video, all I have is the sound ...

Compared to the different tutorials found, I have a unique difference : all of them indicate to install the **InputStream Adaptive** extension.

However, I can only find **InputStream Adaptive Testing**.

I would like to know if this point is the source of my lack of video, and if so, how to install it on Kodi.

Thank you very much.

Cordially.

Benj0B.

**Comment by jlbribeiro** [comment]
Hi @Benj0B,

The most common reason for not finding the InputStream Adaptive add-on on the menus (double check, it's usually installed and disabled) is because your OS/distribution includes it as a separate package.
You don't indicate the OS/Kodi version you're using, but check these issues (I'll list them here for reference, as it seems to be a very common issue):
Raspbian: https://github.com/xbmc/inputstream.adaptive/issues/295#issuecomment-520259178 / https://github.com/xbmc/inputstream.adaptive/issues/333#issuecomment-575893170
Ubuntu: https://github.com/xbmc/inputstream.adaptive/issues/537#issuecomment-716196171 (not quite the same issue, but includes a mention to the nightly PPA + the package name)
LibreELEC: https://github.com/xbmc/inputstream.adaptive/issues/295

(for Raspbian/Ubuntu you should be one package installation away, not exactly sure about LibreELEC situation these days given that thread)

In any case, if you're using some specific distribution it's very likely you'll find a specific package for it; let me know if this was of any help.
Also, a suggestion: next time point out the version of Kodi you're using (at least whether it's Leia or Matrix), as Kodi is in a transition period of sorts.

Best regards.

**Comment by Benj0B** [comment]
Thank you so much jlbribeiro.

I will study this idea this weekend, I will keep you informed of my progress.

Good night.

**Comment by Benj0B** [comment]
This works perfectly by installing the extension from the linux terminal (sudo apt-get install kodi-inputstream-adaptive).

Excellent, thank you very much jlbribeiro!

But I have one very last request:

- On Raspbian, I have no problem playing streaming videos

- On another SD card, I installed an "Android TV" version on Raspberry Pi4. The Kodi application (installed from the PlayStore) does not pose any problem, but on the videos played in streaming, I only have the sound, not the image. Maybe a video codec problem?
Could you direct me to a solution to this problem?

Thanks again.

**Comment by jlbribeiro** [comment]
@Benj0B Glad to read it solved your problem!

To keep issues relevant, as not having video is a completely separate issue, I'd kindly ask you to mark this one as solved (by closing it), and opening a separate one detailing your problem. It's unlikely I'll be able to help you on that second one, but I'm sure an actual dev might.

But before raising one, I'd search for similar GitHub issues or in the Kodi forums, it's possible (and likely) someone has had the same issue? (I was going to point you to the [Disney+ thread in the Kodi forums](https://forum.kodi.tv/showthread.php?tid=353316), but I've seen you've posted there already ;) again: I'd advise you to point out you're using Android [and the relevant software versions], I have the feeling it might be very relevant for your issue).

If you do open a new issue, I'd advise you to include the Kodi logs (with [debugging enabled](https://forum.kodi.tv/showthread.php?tid=323719&pid=2665079#pid2665079)), and possibly point out the specific add-on you're using, so that the devs have a way of replicating your issue if necessary; point out your platform (Android, in this case), Kodi version and add-ons versions.

Let's exclude the possibility this is an issue with Disney+ add-on first (it might not be); briefly skimming the thread above it looks like it might be a more widespread issue with that add-on on Android.

Kind regards, hoping you get your Disney+ working fine!

**Comment by Benj0B** [comment]
OK, thank you very much jlbribeiro !
I will close this post, and follow your advice and the suggested link.
