### ISSUE TITLE
base64 encoded key in m3u8 does not work

### ISSUE THREAD

**Issue by fiplistener** [peak3d/inputstream.adaptive#660]
I have encountered a HLS stream that uses base64 to encode the key directly into a m3u8 playlist

`#EXT-X-KEY:METHOD=AES-128,URI="data:;base64,LF6VBuLEMHdzuFSX3dHuIg==",IV=0x00000000000000000000000000001156`

This works in browsers but fails to play back in nearly every player I've tried including inputstream.adaptive which tries to fetch it from the server

**Comment by glennguy** [comment]
Is it a publicly accessible stream? Otherwise I'm sure we can recreate a local copy. 

I'll have a look and see if this is something trivial to implement.

**Comment by CastagnaIT** [comment]
@fiplistener are you always around here?
if i provide you a test build for kodi 21 can you give a feedback for your problem?

**Comment by Vikassm73** [comment]
I am working on AES-128 stream whose manifest details are as below.

`#EXT-X-SESSION-KEY:METHOD=AES-128,URI="https://key-jiocinema.voot.com/keydelivery/v1/apis/06758e99be484fca56fb/v2.2/aeskeyelastic/get/bpk-vod/jcvod/aes128/6512d96f999890993fb6ce59_v1/6512d96f999890993fb6ce59_v1/aes128.key"`

Which gives error

2023-09-29 11:23:09.293 T:33616   error <general>: CCurlFile::XFILE::CCurlFile::Open - <https://key-jiocinema.voot.com/keydelivery/v1/apis/06758e99be484fca56fb/v2.2/aeskeyelastic/get/bpk-vod/jcvod/aes128/6512d96f999890993fb6ce59_v1/6512d96f999890993fb6ce59_v1/aes128.key> Failed with code 404:
                                                   
2023-09-29 11:23:09.294 T:33616   error <general>: AddOnLog: inputstream.adaptive: CURLOpen returned an error, download failed:

If this is similar, I can try your test build.

**Comment by CastagnaIT** [comment]
@Vikassm73 nope its not the same thing,
the EXT-X-KEY provided by issue author above have URI as data base64 format, that is not an url address

imo should not change your situation with #1388 PR because the code for key url isnt changed,
its possible that you havent provide appropriate headers to Kid request,
see from https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivelicense_key
the point `NOTE: For HLS AES encrypted`
if the problem persist try open a new issue
