### ISSUE TITLE
Manifest refresh for livestreams

### ISSUE THREAD

**Issue by quthla** [peak3d/inputstream.adaptive#77]
Unfortunately, e.g. for pvr.zattoo, the manifest is not being refreshed and as such if one seeked back before, it is impossible to return to live unless stream is restarted.

Would be nice to have a fileitem prop defining an interval in which the manifest should be refreshed completely.

**Comment by peak3d** [comment]
Is this one still open?
b.t.w. its wrong to let addon tell inputream.adaptive how often refresh is called.
It depends on the segment size of the fragmented stream parts and is nothing wich should steered from outside.

**Comment by quthla** [comment]
Yes, it's still open.

Also I noticed that Inputstream won't work if number of segments exceeds uint16_t max (65535) in cases of high timeshift buffer. Would be nice if that could be fixed as well.

**Comment by quthla** [comment]
https://github.com/peak3d/pvr.zattoo/blob/adb34867704ba994394c4bcff45a4a0e68739663/src/client.cpp

Just stumpled upon that commit which never made it to upstream. The manifest update parameter makes the tree update itself regularly?

**Comment by rbuehlma** [comment]
Oh, interesting. shall I cherry pick this commit?:

Is mimetype really required?

**Comment by peak3d** [comment]
@rbuehlma mimetype speeds up stream start (if you include the SetContentLookup(False) because Kodi does not make the extra HEAD request to detect the mime-type.

In general manifest update can be simple (full) which means that after each processed segment the manifest is again retrieved and merged to the existing one.
But there are cases (YouTube e.g.) which provide more intelligent logic to only retrieve changed segments. This helps to reduce download bandwidth.

Best would be to play zattoo in web browser and analyze if manifest update include special headers as etag or sequence / start number attributes. If we know if zattoo uses parameters for this to reduce download size, pls. let me know. 
There are already some possibilituies in inputstream.adaptive.

**Comment by rbuehlma** [comment]
Great. I'll do that and post the result here. Thanks for the explanation.

**Comment by quthla** [comment]
I think I tried it already with update parameter "full" but if I remember it correctly, it didn't change anything about the issue.

Regarding Zattoo web: Manifest is requested every 8 seconds and the client receives the full manifest back.

@peak3d: Is there any fix for the high timeshift buffer issue? You probably know better which variable causes the issue if segment count > 65535

**Comment by rbuehlma** [comment]
Actually, the manifest update does work for me :) I have cherry-picked your commit. Thank you both.

**Comment by rbuehlma** [comment]
How should i include "SetContentLookup". I think this would require a change in Kodi itself or is there a way to set it from the addon?

**Comment by peak3d** [comment]
@rbuehlma https://github.com/liberty-developer/plugin.video.prime_instant/blob/master/default.py#L755-L756

**Comment by rbuehlma** [comment]
missed to mention that I had the binary PVR API in mind :) but in any case, this issue is solve from my point of view.

**Comment by peak3d** [comment]
You can do the same in binary addin IIRC, have seen it recently but forgotten how :-(

**Comment by peak3d** [comment]
https://github.com/xbmc/xbmc/pull/12755
SetContentLookup(false) is called internally if you use the mimetype property

**Comment by rbuehlma** [comment]
Perfekt. Thanks for checking. The start of a stream is already such quick that i cant feel a difference. :) but there will probabaly more for slower internet connections.
