### ISSUE TITLE
Seeking across chapters causing crash (Linux/Mac)

### ISSUE THREAD

**Issue by matthuisman** [peak3d/inputstream.adaptive#783]
Not 100% if this is IA issue yet.

Playing across chapters is fine.
But trying to seek across them is causing Kodi to crash on Linux / Mac

https://forum.kodi.tv/showthread.php?tid=353316&pid=3056971#pid3056971

https://forum.kodi.tv/showthread.php?tid=353316&pid=3057423#pid3057423

I'll try get a debug build running on Linux which should give us a nice crash log with traceback

**Comment by michaelarnauts** [comment]
I have seen reports about this happening on the VTM Go Add-on as well.

**Comment by matthuisman** [comment]
Also hear Netflix also has same issue.

Seems to affect Kodi 18 & 19
I wonder if 2.4.7 has the issue on 18
Ill try get a user to test that.

**Comment by Badsheep** [comment]
Hello Matthuisman,

(I'm the same Badsheep that reported the bug in Kodi forum.)

I saw your message and did the test :  
It doesn't seems to crash with Kodi 18 and input stream.adaptive v2.4.7 !
Still tested on Mac OS.

EDIT-
Hum... not sure...
It did crashed.
Well I'm not sure at 100%.
Have to test a bit more.

**Comment by matthuisman** [comment]
ok, if 2.4.7 seems at least better, then it narrows down to one of the PRs listed here: https://github.com/xbmc/inputstream.adaptive/pull/711

@Badsheep Can you try the below build and report back your findings?
https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-784/1/artifact/cmake/addons/build/zips/inputstream.adaptive+osx-x86_64/inputstream.adaptive-2.6.23.zip

**Comment by Badsheep** [comment]
Yes with pleasure !
But ain’t it the version for Kodi 19 ?

**Comment by matthuisman** [comment]
Yes. Please try on Kodi 19 on mac

**Comment by Badsheep** [comment]
OK it seems more more stable :)
but I still had one crash while pressing "Stop" in Disney + add-on.
[Log here](https://paste.kodi.tv/zudequceko.kodi).

**Comment by matthuisman** [comment]
Does the other version (from repo) also crash when you stop? Or does my
version I posted above introduce that issue?

**Comment by Badsheep** [comment]
No it’s worse with the repo version.
I’m testing the chapters bugs, as you asked, but for me the most annoying bug is this « stop » bug.
The version above did improve the situation, but it’s not completely solved.

**Comment by matthuisman** [comment]
My version above is simply reverting a previous commit..

So the stop bug has always been present but you only noticed earlier?

Is it also in Kodi 18? And on your raspberry pi?

**Comment by Badsheep** [comment]
No it happened in an upgrade.
I need a bit of time to collect informations more precise, I’ll be back un a few hours with a complete sum-up.

**Comment by matthuisman** [comment]
Yes please. I'm getting conflicting info..

**Comment by Badsheep** [comment]
I’m on Mac OS only.

**Comment by Badsheep** [comment]
OK, here’s all my test process.
At the beginning, my config was :

Mac OS, Kodi 18.4, input stream.adaptive v2.4.2, addons : Netflix

Everything worked fine.
Then I wanted to install Disney + addon.
I installed it but I had to upgrade input stream.adaptive.

So now we are here :

Mac OS, Kodi 18.4, input stream.adaptive v2.4.8, addons : Netflix, Disney +

That’s where I noticed the bug (reported [here](https://forum.kodi.tv/showthread.php?tid=353316&pid=3056393#pid3056393) and [here](https://forum.kodi.tv/showthread.php?tid=353316&pid=3056919#pid3056919)) : when I Stop the movie, it often crashes.
In the Kodi forum you said it could be related to the [ThomB bug](https://forum.kodi.tv/showthread.php?tid=353316&pid=3057423#pid3057423) (crash when skipping chapters)

To check if it was related to Kodi 18, I did the test :

Mac OS, Kodi 19.1, input stream.adaptive v2.6.23, addons : Netflix, Disney +

Same issue.
To check is it was Mac OS related, I did the test :

Windows, Kodi 19.1, input stream.adaptive v2.6.23, addons : Netflix, Disney +

The issue seems to disappear !
That’s where you ask to try your 2.6.23 modified version :

Mac OS, Kodi 19.1, input stream.adaptive v2.6.23 modified, addons : Netflix, Disney +

The issue seems to be very very attenuated, only happened once in lot of tests.

To be sure before posting all this text, I tried to switch back to inputstream adaptive on the Kodi Repo : it crashed the first time I pressed Stop on a movie. So the modified version is definitely better !

**Comment by matthuisman** [comment]
@Badsheep
I've created a new issue for the stopping causing crash: https://github.com/xbmc/inputstream.adaptive/issues/787

Lets keep this issue for seeking across chapters bug only.
**With the above build I sent you, that fixes seeking across chapter for you right?**

**Comment by Badsheep** [comment]
Yes

**Comment by thombet** [comment]
@matthuisman 

I tried to test with [the build you sent in the forum](https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-786/1/artifact/cmake/addons/build/zips/inputstream.adaptive+osx-x86_64/inputstream.adaptive-2.4.8.zip) on Kodi 18.9 MacOS but for some reason there is no chapter listed in the OSD "bookmarks" menu so I cannot confirm whether it solves the issue :(
Any settings in Disney+ add-on that would prevent the chapters to be created?

**Comment by matthuisman** [comment]
umm no. no reason the chapters / bookmarks should be affected.
you sure they usually work in 18.9?
You can still test by seeking / ffwding or using the skip credits setting?

**Comment by thombet** [comment]
> umm no. no reason the chapters / bookmarks should be affected.
> 
> you sure they usually work in 18.9?

I played a local MKV file which contains chapters and they were listed so I think they work.
@Badsheep do you have chapters on MacOS Kodi 18 when playing a Marvel movie in Disney+ add-on? (e.g. Iron Man 2)

> 
> You can still test by seeking / ffwding or using the skip credits setting?

Actually my initial assumption that Kodi crashes when seeking across chapters was wrong: what happened was that `Skip credits` was enabled so at the end of the movie the playback jumped to the end of the movie (which is similar to a "stop" command I guess) so the bug I was seeing is the one reported by Badsheep.
According to me, the only remaining bug with chapters is when selecting a different chapter from the OSD and I cannot test this for some reason on MacOS 😞 

I have another working environment with OSMC Kodi 19.1 which is having the bug. If you provide me a modified version of InputStream Adaptive for this platform I could test if the bug is gone (I think I could have reused the link you gave to Badsheep above but it is broken).

**Comment by Badsheep** [comment]
> I played a local MKV file which contains chapters and they were listed so I think they work.
> @Badsheep do you have chapters on MacOS Kodi 18 when playing a Marvel movie in Disney+ add-on? (e.g. Iron Man 2)

You're right, I never paid attention to chapters but I just some quick tests : 

With Mac OS, Kodi 18, chapters work with local but not with streaming sources (Neftlix or Disney+)
With Mac OS, Kodi 19, chapters work with local and some Disney+ movies (including Antman 2), but not with Netflix.

**Comment by glennguy** [comment]
Kodi 18 has support for chapters with inputstreams, however the UI/OSD doesn't have the same support. Kodi 19 shows the little white dots on the OSD timeline. So you can still play inputstream content with multiple 'chapters' i.e Disney+ in Kodi 18

**Comment by thombet** [comment]
> Kodi 18 has support for chapters with inputstreams, however the UI/OSD doesn't have the same support. Kodi 19 shows the little white dots on the OSD timeline. So you can still play inputstream content with multiple 'chapters' i.e Disney+ in Kodi 18

Thanks @glennguy for the clarification.
Is there a way to display chapters and to jump to a specific chapter in Kodi 18 so that I test the build sent by Matt?

**Comment by glennguy** [comment]
I think you can still skip chapters with up/down buttons, just that the OSD doesn't show it. Haven't seen in a while so not sure if my memory can tell you any more

**Comment by thombet** [comment]
Surprisingly the up arrow on my MacOS keyboard seeks 10 minutes ahead instead of jumping to the next chapter.

Anyway I am thinking more and more that this bug is actually the same as the one described in #787.
I propose to wait for #787 to be fixed and then to check again if this one still exists.

**Comment by Badsheep** [comment]
I think the arrows jump chapter to chapter if they exist, or seek 10 minutes when there is no chapters.

**Comment by matthuisman** [comment]
ok, I can reproduce this issue on RPI4 LibreELEC 10.0.0

Its definitely when seeking across chapters (a bunch of tiny chapters in credits)
Disney+ seeks pass these by default to skip credits.

Seeking around in the first chapter is fine
And letting it play over the chapters is fine.
its just when seeking or ffwding over them

This is fresh LibreELEC 10 and only Disney+ installed
IA 19.0.0.1

here are some other users provided logs as well
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/7575395/kodi.log)
[kodi_crashlog_20211120223527.log](https://github.com/matthuisman/slyguy.addons/files/7575396/kodi_crashlog_20211120223527.log)

**I'll start trying to narrow it down :)**

More findings:
Its something in the video track.
Changing IA to AUDIO only = no crashing.
Changina IA to VIDEO only = crashes
Crash happens both with latest Widevine (4.10.2252.0) and old widevine (4.10.1679.0) blobs

Here are my own logs:
[kodi.old.log](https://github.com/xbmc/inputstream.adaptive/files/7577320/kodi.old.log)
[kodi_crashlog_20211121225518.log](https://github.com/xbmc/inputstream.adaptive/files/7577321/kodi_crashlog_20211121225518.log)
(ive disabled any slyguy proxy stuff and any xbmc.player or other python threads)

**Comment by argymeg** [comment]
I noticed yesterday I'm no longer affected by this (IA 19.0.3.1 / Disney+ 0.11.5 / Widevine 4.10.2449.0). Not sure when or where it might have been fixed, though the most recent update I believe was Widevine only a few days ago.

**Comment by matthuisman** [comment]
That's really good news. 
I pushed that newer widevine just a few days ago... So assume something in that sorted it?

**Comment by CastagnaIT** [comment]
assume now working?
we can close?

**Comment by Weissnix4711** [comment]
Yup, all good now.
