### ISSUE TITLE
Widevine license acquisition failed

### ISSUE THREAD

**Issue by Vikassm73** [peak3d/inputstream.adaptive#919]
Working on Matrix with updated Inputsream and Widevine.

Getting error, 
{"errorcode":371000005,"errormsg":"Widevine license acquisition failed >> Verified media path cannot be verified","errorid":"e06596cb-1362-42bd-bcd8-19d0ee3bb81b"}

inputstream.adaptive: License server returned failure
inputstream.adaptive: License update not successful (no keys)

In the browser, it is showing below details for the license url

Request URL: https://spapi.zee5.com/widevine/getLicense
Request Method: POST

Used following code

`        
       
       lic_url='https://spapi.zee5.com/widevine/getLicense'
       headers.update({'customdata': customdata})
       headers.update({'nl': nl})
       license_key = '%s|%s|R{SSM}|' % (lic_url,urllib_parse.urlencode(headers))
       play_item.setProperty('inputstream.adaptive.license_key', license_key)
`

There is also one key. but don't know it is required or not as I don't find usage of it in any header information.

drm_key_id: "66701115-8740-4228-9d5b-955a56aaa077" 

Please advise.

[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/8339242/kodi.log)

**Comment by glennguy** [comment]
That key id is the one being sent to the the decrypter so that's not the issue 

Verified Media Path (VMP) is the problem and unfortunately there's nothing that can be done from our side.

Further info in most of these issues: https://github.com/xbmc/inputstream.adaptive/issues?q=is%3Aissue+vmp+is%3Aclosed

Basically the provider had configured their content to only be playable on devices that either are verified (e.g Chrome on windows, signed with widevine certificate) or platforms that have an exception (can't remember if that's Linux arm or Linux x64...). Android of course will work fine as long as the device can be provisioned properly for widevine, not in the case of very cheap boxes or that have fake WV certification.

**Comment by CastagnaIT** [comment]
~by reading this: https://github.com/Dash-Industry-Forum/dash.js/issues/1924#issuecomment-302034800~

~another solution to try is add the server certificate:~
~https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptiveserver_certificate~

~@glennguy the request to get the certificate before the license, is not possible do it?~

PS.

nevemind i read that require sign the application...
i will add something in Wiki

**Comment by Vikassm73** [comment]
Does this should play in Dash? (Which I have tested and not playing)

https://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html

**Comment by glennguy** [comment]
> Does this should play in Dash? (Which I have tested and not playing)

Not really sure what you're trying to ask. The default video plays fine using the player in that link... what does this have to do with Kodi/inputstream.adaptive?

**Comment by Vikassm73** [comment]
Nothing to do with Kodi/inputstream.adaptive. Just wanted to test whether it can be played in the above link if I provide required license server as well as header info but it does not work. 

Will this work in kodi under Android?

**Comment by glennguy** [comment]
Ok I think I understand - yes that link should be able to do license acquisition properly, as long as your browser is signed with widevine key. This is where smaller/forked browser or browser compiled from source would fail due to VMP, and also Kodi.

VMP doesn't apply to Android, as long as the device can be provisioned L3/L1 then it's all good. Often installing a custom rom will loose the L1 capability, and cheap chinese devices that are marketed as L1 are just fake L1 (DRM Info app will report L1, but provisioning fails).

**Comment by Vikassm73** [comment]
Tried same in Bluestack Android installed in windows. USED modified code

`        


        lic_url="https://spapi.zee5.com/widevine/getLicense"
        post_data = urllib_parse.quote_plus('{"customdata":"%s","nl":"%s","drm_info":[D{SSM}],"kid":"%s"}' % 
                           (customdata,nl,drm_key))
        license_key = lic_url + '|'+urllib_parse.urlencode(headers)+'|' + post_data + '|'
        play_item.setProperty('inputstream.adaptive.license_key', license_key)
`

2022-03-28 11:33:50.153 T:6623    DEBUG <general>: AddOnLog: inputstream.adaptive: Entering encryption section
2022-03-28 11:33:50.201 T:6623    ERROR <general>: AddOnLog: inputstream.adaptive: Unable to initialize media_drm
2022-03-28 11:33:50.201 T:6623    ERROR <general>: AddOnLog: inputstream.adaptive: OpenDRMSystem failed
2022-03-28 11:33:50.202 T:6623    DEBUG <general>: AddOnLog: inputstream.adaptive: Session::~Session()
2022-03-28 11:33:50.202 T:6623    DEBUG <general>: AddOnLog: inputstream.adaptive: WVDecrypter destructed

Do I have made any mistake?

[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/8360140/kodi.log)

**Comment by CastagnaIT** [comment]
you have to use a real android widevine certified device not a VM
and i think that you should use also an android user-agent

**Comment by Vikassm73** [comment]
Thanks @CastagnaIT for your advice. Unfortunately I don't have valid Android box. I have tried replacing User-Agent but result is the same,

**Comment by Vikassm73** [comment]
Worked perfectly under Linux environment. Thanks @CastagnaIT @glennguy for your help.

**Comment by basilgello** [comment]
https://github.com/Avalonswanderer look for his article on arXiv and the repos :)
